[preface]
== Бърз Речник

Бързият речник съдържа много от термините използвани във връзка с биткойн. Тези термини се използват през цялата книга, затова ги отбележете за бърза референция.

адрес::
    Биткойн адрес изглежда по следния начин: +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. Той съдържа низ от букви и числа, започващия с "1" (числото едно). Точно както поисквате от други  да ви изпратят имейл на вашия имейл адрес,  по същия начин бихте поискали да ви изпратят биткойн на вашия биткойн адрес.((("биткойн адрес")))((("адрес", see="биткойн адрес")))((("публичен ключ", see="биткойн адрес")))

bip::
    Bitcoin Improvement Proposals (BIP - Предложения за подобряване на Биткойн). Това са набор от предложения, направени от членове на биткойн общността за подобрение на биткойн. Например, BIP0021 е предложение за подобрение на URI биткойн адрес схемата (Uniform Resource Identifier scheme) ((("bip"))) 

биткойн::
    Името на валутна единица (монетата), мрежата и софтуера. ((("биткойн"))) 

блок::
    Група транзакции, маркирани с времева щампа (timestamp) и цифров отпечатък (fingerprint) от предишния блок. Хедърът на блока е хеширан да създаде доказателство за работа (proof of work), като така валидира транзакциите. Валидните блокове са добавени към главната блок верига (blockchain) чрез мрежови консенсус. ((("блок")))

blockchain::
	A list of validated blocks, each linking to its predecessor all the way to the genesis block.((("blockchain")))
	
confirmations::
	Once a transaction is included in a block, it has one confirmation. As soon as _another_ block is mined on the same blockchain, the transaction has two confirmations, and so on. Six or more confirmations is considered sufficient proof that a transaction cannot be reversed.((("confirmations")))

difficulty::
	A network-wide setting that controls how much computation is required to produce a proof of work.((("difficulty")))

difficulty target::
 	A difficulty at which all the computation in the network will find blocks approximately every 10 minutes.((("target difficulty")))

difficulty retargeting::
	A network-wide recalculation of the difficulty that occurs once every 2,106 blocks and considers the hashing power of the previous 2,106 blocks.((("difficulty retargeting")))
	
fees::
	The sender of a transaction often includes a fee to the network for processing the requested transaction.  Most transactions require a minimum fee of 0.5 mBTC.((("fees")))

hash::
	A digital fingerprint of some binary input.((("hash")))

genesis block::
	The first block in the blockchain, used to initialize the cryptocurrency.((("genesis block")))
	
miner::
A network node that finds valid proof of work for new blocks, by repeated hashing.((("miner")))

network::
A peer-to-peer network that propagates transactions and blocks to every bitcoin node on the network.((("network")))
	
Proof-Of-Work::
	A piece of data that requires significant computation to find. In bitcoin, miners must find a numeric solution to the SHA256 algorithm that meets a network-wide target, the difficulty target. ((("proof-of-work")))

reward::
An amount included in each new block as a reward by the network to the miner who found the Proof-Of-Work solution. It is currently 25BTC per block.((("reward")))

secret key (aka private key)::
	The secret number that unlocks bitcoins sent to the corresponding address.  A secret key looks like +5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh+.((("secret key")))((("private key", see="secret key")))
	
transaction::
In simple terms, a transfer of bitcoins from one address to another. More precisely, a transaction is a signed data structure expressing a transfer of value. Transactions are transmitted over the bitcoin network, collected by miners, and included into blocks, made permanent on the blockchain.((("transaction")))

wallet::
Software that holds all your bitcoin addresses and secret keys. Use it to send, receive, and store your bitcoin.((("wallet"))) 