[前言]
== 常用詞彙

這份常用詞彙表囊括了許多跟比特幣有關的用語，本書常會提及它們，建議您在此處放置書籤，方便查詢。

位址::
    比特幣的位址長得像這樣：+1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+，它由一串英文字母與數字所組成，而且開頭一定是「1」（數字的 1 ）。就像寄電子郵件一樣，別人可以把比特幣傳送到你的比特幣位址裡。((("比特幣地址")))((("位址", 見="比特幣位址")))((("公開金鑰", 見="比特幣為位址"))

bip::
    Bitcoin Improvement Proposals.  A set of proposals that members of the bitcoin community have submitted to improve bitcoin.  For example, BIP0021 is a proposal to improve the bitcoin uniform resource identifier (URI) scheme.((("bip"))) 

比特幣 ::
    貨幣單位的名稱（幣），它也是一個網路、一套軟體。((("比特幣"))) 

區塊::
    A grouping of transactions, marked with a timestamp, and a fingerprint of the previous block. The block header is hashed to produce a proof of work, thereby validating the transactions. Valid blocks are added to the main blockchain by network consensus.((("block")))

區塊鏈::
	一份囊括有效區塊的清單，每個區塊都和它的老祖先──創世區塊有所連結。((("區塊鏈")))
	
確認::
	一旦交易紀錄收錄在區塊裡，它就經過了一次確認；在同一區塊鏈上找到另一個區塊時，這筆交易紀錄就有了第兩次確認，以此類推。當一筆交易紀錄經過六次以上確認後，就足以保證這筆交易無法取消。((("確認")))

挖礦難度::
	遍布整個比特幣網路的設定，它控制了產生工作證明所需的運算量。((("挖礦難度")))

目標難度::
 	一個變動的值，比特幣網路依照總運算量，將產生新區塊的週期控制在每 10 分鐘左右產生一個新區塊。((("目標難度")))

難度調整::
	每產生 2,106 個區塊，比特幣網路就會依照前 2,106 個區塊的算力重新調整挖礦難度。
	
手續費::
	為了讓交易順利執行，傳送比特幣的一方通常要支付手續費給比特幣網路。大部分的交易都需要支付一筆 0.5 mBTC 的基本手續費。

hash::
	A digital fingerprint of some binary input.((("hash")))

創世區塊::
	區塊鏈中第一個區塊，用來啟動虛擬貨幣。((("創世區塊")))
	
礦工::
網路中的一個節點，為了產生新的區塊，它透過重複地運算去找尋有效的工作證明。((("礦工")))

比特幣網路::
一個對等網路，它會將交易紀錄及區塊傳送至比特幣網路中的每個節點。((("比特幣網路")))
	
工作量證明機制::
	需要透過大量運算才能尋獲的資料。在比特幣的世界裡，礦工必須使用 SHA256 演算法找到符合「目標難度」的特定解。((("工作量證明機制")))

酬賞::
一定數量的獎賞，目前是每區塊 25BTC。當礦工找到工作量證明機制的有效解時，比特幣網路就會發送新生區塊中的比特幣。

私密金鑰（又稱私人金鑰）::
	解鎖比特幣錢包的密碼。一組私密金鑰看起來就像這樣：+5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh+。((("私密金鑰")))((("私人金鑰", 見="私密金鑰")))
	
交易::
簡單來說，交易是把比特幣從一個位址傳送到另一個位址。如果要說得更精準一點，交易是記錄了貨幣移轉的一種資料結構簽證。交易在比特幣網路中傳輸、被礦工收集、納入區塊中，最後永久成為區塊鏈的一部分。((("交易")))

比特幣錢包::
比特幣錢包是一套軟體，它記錄了使用者所有的位址及私密金鑰，也可以用來傳送、接收及存放比特幣。 