[[ch10]]
==  Seguridad de Bitcoin

((("Seguridad", id = "ix_ch10-asciidoc0", rango = "startofrange"))) Asegurar bitcoin es un reto porque bitcoin no es una referencia abstracta a su valor, como un saldo en una cuenta bancaria. Bitcoin es muy parecido a dinero en efectivo u oro digital. Usted probablemente ha escuchado la expresión, "la posesión es nueve décimas partes de la ley." Pues bien, en bitcoin, la posesión es de diez décimas partes de la ley. La posesión de las llaves para desbloquear el bitcoin es equivalente a la posesión de dinero en efectivo o un trozo de metal precioso. Usted puede perder, extraviarlo, tenerlo robado o accidentalmente dar la cantidad incorrecta de alguien. En cada uno de estos casos, los usuarios no tienen ningún recurso, al igual que si cayera efectivo en una acera pública. 

Sin embargo, bitcoin tiene capacidades que el efectivo, el oro y las cuentas bancarias no lo hacen. Una cartera bitcoin, que contiene las llaves, se pueden copiar como cualquier archivo. Se puede almacenar en múltiples copias, incluso impreso en papel para copia de seguridad de copia impresa. No se puede "sostener" las cuentas de efectivo, oro, o bancarios. Bitcoin es lo suficientemente diferente de todo lo que ha llegado antes que nosotros necesitamos pensar en Bitcoin seguridad en una forma novedosa también. 

=== Principios de Seguridad

((("Seguridad", "principios de"))) El principio básico de Bitcoin es la descentralización y tiene importantes implicaciones para la seguridad. Un modelo centralizado, como un banco tradicional o red de pagos, depende del control de acceso y de investigación de antecedentes para mantener malos actores del sistema. En comparación, un sistema descentralizado como bitcoin empuja a la responsabilidad y control a los usuarios. Dado que la seguridad de la red se basa en la prueba de trabajo, no en el control de acceso, la red puede ser abierta y no se requiere el cifrado para el tráfico Bitcoin. 

En una ((("sistema de pago con tarjeta de crédito"))) ((("redes de pago, tradicional"))) red de pago tradicionales, tales como un sistema de tarjetas de crédito, el pago es de composición abierta, ya que contiene identificador privado del usuario (el número de tarjeta de crédito). Después de la carga inicial, cualquier persona con acceso al identificador puede "coger" los fondos y cargarlos del propietario y otra vez. De este modo, la red de pagos tiene que ser asegurada de extremo a extremo con encriptación y debe asegurarse de que no hay ((("espías"))) fisgones o intermediarios pueden comprometer el tráfico de pagos, en tránsito o cuando se almacena (en reposo) . Si una mal actor gana acceso y para el sistema, puede comprometer transacciones corrientes _y_ testigos de pago que pueden utilizarse para crear nuevas transacciones. Peor aún, cuando se ve comprometida los datos de clientes, los clientes están expuestos a robo de identidad y deben tomar medidas para evitar el uso fraudulento de las cuentas comprometidas.

Bitcoin es dramáticamente diferente. Una transacción bitcoin autoriza solamente un valor específico a un destinatario específico y no puede ser falsificado o modificado. No reveló ninguna información privada, como la identidad de las partes, y no puede ser utilizado para autorizar los pagos adicionales. Por lo tanto, una red de pago bitcoin no necesita ser encriptada o protegida contra escuchas. De hecho, usted puede difundir transacciones Bitcoin más de un canal abierto al público, tales como Wi-Fi o Bluetooth sin garantía, sin pérdida de seguridad.

El modelo de seguridad descentralizada de Bitcoin pone mucho poder en manos de los usuarios. Con ese poder viene la responsabilidad de mantener la confidencialidad de las claves. Para la mayoría de los usuarios que no es fácil de hacer, sobre todo en los dispositivos informáticos de propósito general tales como smartphones o portátiles conectados a Internet. Aunque el modelo descentralizado de bitcoin impide el tipo de compromiso en masa comparado con tarjetas de crédito, muchos usuarios no son capaces de asegurar adecuadamente sus llaves y ser hackeado, uno por uno.


==== Desarrollando Sistemas Bitcoin de Forma Segura

((("Bitcoin", "la seguridad del sistema"))) ((("seguridad", "controles centralizados y"))) El principio más importante para los desarrolladores de Bitcoin es la descentralización. La mayoría de los desarrolladores estarán familiarizados con modelos de seguridad centralizadas y podrían estar tentados a aplicar estos modelos a sus aplicaciones Bitcoin, con resultados desastrosos. 

La seguridad de Bitcoin se basa en el control descentralizado de llaves y en la validación independiente de las transacciones por los mineros. Si quieres aprovechar la seguridad de Bitcoin, es necesario asegurarse de que permanezca en el modelo de seguridad de Bitcoin. En términos simples: no tomar el control de las llaves lejos de los usuarios y no tome las transacciones fuera de la cadena de bloques. 

Por ejemplo, muchos casas de cambio de Bitcoin concentraban primero todos los fondos de los usuarios en una sola cartera "caliente" con claves almacenadas en un solo servidor. Tal diseño elimina el control de los usuarios y centraliza el control de las llaves en un solo sistema. Muchos de estos sistemas han sido hackeados, con consecuencias desastrosas para sus clientes. 

((("Transacciones", "despegando blockchain"))) Otro error común es tomar las transacciones "fuera de la cadena de bloques" en un esfuerzo equivocado para reducir las tasas de transacción o acelerar el procesamiento de transacciones. Un sistema de "blockchain off" registrará las transacciones en un libro de contabilidad interna, centralizada y sólo ocasionalmente sincronizarlos con la cadena de bloques de bitcoin. Esta práctica, de nuevo, sustitutos descentralizado bitcoin de seguridad con un enfoque exclusivo y centralizado. Cuando las transacciones se blockchain apagado, libros de contabilidad centralizados inadecuadamente asegurados pueden ser falsificados, desviar fondos y agotando las reservas, desapercibido. 

A menos que usted está dispuesto a invertir fuertemente en la seguridad operacional, múltiples capas de control de acceso, y las auditorías (como los bancos tradicionales hacen) usted debe pensar cuidadosamente antes de tomar fondos fuera del contexto de seguridad descentralizada de Bitcoin. Incluso si usted tiene los fondos y la disciplina para implementar un modelo de seguridad robusto, un diseño tan sólo replica el modelo de fragilidad de las redes financieras tradicionales, plagado por el robo de identidad, la corrupción y la malversación de fondos. Para aprovechar el modelo de seguridad descentralizada única de Bitcoin, hay que evitar la tentación de arquitecturas centralizadas que podrían sentirse familiar, pero en última instancia, subvertir la seguridad de Bitcoin.

==== La Raíz de la Confianza

((("Raíz de confianza"))) ((("seguridad", "raíz de confianza"))) La arquitectura de seguridad tradicional se basa en un concepto llamado el _raiz de confianza_, que es un núcleo de confianza utilizado como base para la seguridad del sistema o aplicación general. La arquitectura de seguridad se desarrolla alrededor de la raíz de la confianza como una serie de círculos concéntricos, como las capas de una cebolla, que se extiende la confianza hacia el exterior del centro. Cada capa se basa en la capa interna más confianza que utilizan los controles de acceso, firmas digitales, cifrado y otras primitivas de seguridad. Como los sistemas de software se hacen más complejos, es más probable que contenga errores, que los hacen vulnerables a comprometer la seguridad. Como resultado, un sistema de software que se convierte más complejo, más difícil es de asegurar. La raíz del concepto de fideicomiso asegura que la mayor parte de la confianza que se coloca dentro de la parte menos compleja del sistema, y ​​por lo tanto menos vulnerables, las partes del sistema, mientras que el software más complejo es en capas alrededor. Esta arquitectura de seguridad se repite a diferentes escalas, estableciendo primero una raíz de confianza en el hardware de un solo sistema, y ​​luego extender esa raíz de la confianza a través del sistema operativo para los servicios del sistema de nivel superior, y finalmente a través de muchos servidores en capas en los círculos concéntricos de disminución de la confianza. 

La arquitectura de seguridad Bitcoin es diferente. En Bitcoin, el sistema de consenso crea un libro de contabilidad público de confianza que está completamente descentralizado. Una cadena de bloques validada correctamente utiliza el bloque génesis como la raíz de la confianza, la construcción de una cadena de confianza hasta el bloque actual. Los sistemas Bitcoin pueden y deben utilizar la cadena de bloques como su raíz de confianza. Al diseñar una aplicación bitcoin compleja que consta de los servicios en muchos sistemas diferentes, usted debe examinar cuidadosamente la arquitectura de seguridad con el fin de determinar dónde se va a colocar la confianza. En última instancia, la única cosa que debe ser de confianza expresamente es una cadena de bloques plenamente validada. Si su aplicación de forma explícita o implícitamente confiere confianza en cualquier cosa menos la cadena de bloques, debería ser una fuente de preocupación porque introduce vulnerabilidad. Un buen método para evaluar la arquitectura de seguridad de la aplicación es considerar cada componente individual y evaluar un escenario hipotético donde el componente está completamente comprometido y bajo el control de un agente malicioso. Tome cada componente de su aplicación, a su vez, y evaluar los impactos sobre la seguridad general si ese componente se ve comprometida. Si la aplicación ya no es segura cuando los componentes están en peligro, que demuestra que ha perdido la confianza en esos componentes. Una aplicación bitcoin sin vulnerabilidades debe ser vulnerables solamente a un compromiso del mecanismo de consenso bitcoin, lo que significa que su raíz de confianza se basa en la parte más fuerte de la arquitectura de seguridad bitcoin. 

Los numerosos ejemplos de casas de cambio de Bitcoin hackeados sirven para subrayar este punto porque su arquitectura y diseño de seguridad falló, incluso bajo el escrutinio más casual. Estas implementaciones centralizadas habían invertido confianza explícitamente en numerosos componentes fuera de la cadena de bloques de bitcoin, como carteras calientes, bases de datos centralizadas de contabilidad, claves de cifrado vulnerables, y esquemas similares. 


=== Mejores Prácticas de Seguridad para el usuario 

((("Seguridad", "usuario", id = "ix_ch10-asciidoc1", rango = "startofrange"))) ((("la seguridad del usuario", id = "ix_ch10-asciidoc2", rango = "startofrange")) ) Los seres humanos han utilizado los controles de seguridad físicos durante miles de años. En comparación, nuestra experiencia con la seguridad digital es menor de 50 años de edad. ((("Sistemas operativos, de seguridad y de bitcoin"))) sistemas operativos de propósito general modernos no son muy seguro y no es particularmente adecuado para el almacenamiento de dinero digital. Nuestros equipos están constantemente expuestos a las amenazas externas a través siempre de las conexiones a Internet. Corren miles de componentes de software de cientos de autores, a menudo con el acceso sin restricciones a los archivos del usuario. Una sola pieza de software ilegítimo, entre los muchos miles instalados en el equipo, puede poner en peligro sus claves y archivos, y robar cualquier bitcoin almacenada en aplicaciones de monedero. El nivel de mantenimiento de computadoras requerido para mantener un ordenador libre de virus y troyanos libre está más allá del nivel de habilidad de todos, por una pequeña minoría de los usuarios de computadoras. 

A pesar de décadas de investigación y los avances en la seguridad de la información, los activos digitales siguen siendo lamentablemente vulnerables a un adversario determinado. Incluso los sistemas más altamente protegidos y restringidos, en las empresas de servicios financieros, agencias de inteligencia y los contratistas de defensa, se incumplen con frecuencia. Bitcoin crea activos digitales que tienen un valor intrínseco y pueden ser robados y desviados a los nuevos propietarios al instante y de manera irrevocable. ((("hackers"))) Esto crea un incentivo enorme para los piratas informáticos. Hasta ahora, los hackers tuvieron que convertir la información de identidad o de cuentas fichas, tales como tarjetas de crédito y cuentas bancarias, en valor después de comprometer ellos. A pesar de la dificultad de la esgrima y el lavado de la información financiera, hemos visto robos cada vez más intensos. En bitcoin se intensifica este problema, ya que no necesita ser cercada o lavados; es el valor intrínseco de un activo digital. 

Afortunadamente, bitcoin también crea los incentivos para mejorar la seguridad informática. Mientras que antes el riesgo de compromiso ordenador era vaga e indirecta, bitcoin hace que estos riesgos sean claros y evidentes. Sosteniendo bitcoin en un equipo sirve para enfocar la mente del usuario en la necesidad de mejorar la seguridad informática. Como consecuencia directa de la proliferación y la creciente adopción de bitcoin y otras monedas digitales, hemos visto una escalada de ambas técnicas de hacking y soluciones de seguridad. En términos simples, los hackers tienen ahora un objetivo muy jugoso y los usuarios tienen un claro incentivo para defenderse. 

Durante los últimos tres años, como resultado directo de la adopción de Bitcoin, hemos visto una enorme innovación en el ámbito de la seguridad de la información en forma de cifrado de hardware, almacenamiento y carteras hardware clave, la tecnología multi-firma y depósito en garantía digital. En las siguientes secciones examinaremos varias mejores prácticas para la seguridad del usuario práctico.

==== Almacenamiento Físico de Bitcoins

((("Copias de seguridad", "carteras de almacenamiento en frío"))) ((("almacenamiento, físicos" "bitcoin"))) ((("carteras de almacenamiento en frío"))) ((("billeteras de papel" ))) ((("la seguridad del usuario", "almacenamiento bitcoin físico"))) Porque la mayoría de los usuarios son mucho más cómodos con la seguridad física de seguridad de la información, un método muy eficaz para la protección de bitcoins es convertirlos en forma física. Las claves Bitcoin no son más que números largos. Esto significa que se pueden almacenar en una forma física, tal como impreso en papel o grabada en una moneda de metal. Asegurar las claves y llega a ser tan simple como asegurar físicamente la copia impresa de las claves de Bitcoin. Un juego de claves de Bitcoin que se imprime en el papel se llama una "billetera de papel", y hay muchas herramientas gratuitas que pueden ser utilizados para crearlos. Personalmente mantengo la gran mayoría de mis bitcoins (99% o más) almacenados en las carpetas de papel, cifrados con BIP0038, con múltiples copias encerrados en cajas fuertes. Mantener offline bitcoin se llama "almacenaje en frio" y es una de las técnicas de seguridad más eficaces. Un sistema de almacenamiento en frío es uno donde las claves se generan en un sistema sin conexión (uno nunca conectado a Internet) y se almacenan en línea, ya sea en papel o en soporte digital, como un lápiz de memoria USB. 

==== Carteras de Hardware

((("carteras de hardware"))) ((("la seguridad del usuario", "carteras de hardware"))) ((("carteras", "hardware"))) En el largo plazo, la seguridad de bitcoin cada vez tomará la forma de carteras hardware a prueba de manipulaciones. A diferencia de una computadora de escritorio o teléfono inteligente, una cartera de hardware bitcoin tiene un solo propósito: almacenar bitcoins de forma segura. Sin el software de propósito general de compromiso y con interfaces limitadas, carteras de hardware pueden ofrecer un nivel casi infalible de seguridad a los usuarios no expertos. Espero ver que las carteras de hardware se conviertan en el método predominante de almacenamiento bitcoin. Para un ejemplo de como una cartera de hardware, consulte el ((("cartera Trezor"))) http://www.bitcointrezor.com/[Trezor].

==== Balance de Riesgo

((("Riesgo de seguridad"))) ((("la seguridad del usuario", "riesgo, equilibrando"))) Aunque la mayoría de los usuarios están justamente preocupados por el robo de bitcoin, existe un riesgo aún mayor. Los archivos de datos se pierden todo el tiempo. Si contienen Bitcoin, la pérdida es mucho más dolorosa. En el esfuerzo por asegurar sus carteras Bitcoin, los usuarios deben tener mucho cuidado de no ir demasiado lejos y terminar perdiendo el bitcoin. En julio de 2011, una conciencia bitcoin conocido y proyecto de educación perdieron casi 7.000 bitcoins. En su esfuerzo para evitar el robo, los propietarios habían implementado una compleja serie de copias de seguridad cifradas. Al final perdieron accidentalmente las claves de cifrado, por lo que las copias de seguridad sin valor y perder una fortuna. Como ocultar dinero enterrándolo en el desierto, si usted asegura su bitcoin demasiado bien que no podría ser capaz de encontrarlo de nuevo.

==== Diversificación de Riesgo

((("La seguridad del usuario", "riesgo, diversificando"))) ¿Quieres que llevar todo su patrimonio neto en efectivo en su cartera? La mayoría de la gente consideraría que es imprudente, sin embargo, los usuarios a menudo bitcoin mantienen todos sus bitcoin en una sola cartera. En lugar de ello, los usuarios deben distribuir el riesgo entre los múltiples y diversas carteras Bitcoin. Usuarios prudentes mantendrán sólo una pequeña fracción, tal vez menos del 5%, de sus bitcoins en una billetera en línea o móvil como "dinero de bolsillo". El resto debe ser dividida entre unos pocos mecanismos de almacenamiento diferentes, tales como una cartera de escritorio y fuera de línea (almacenamiento en frío).

==== Multi-firma y Gobernanza

((("Corporaciones, gobierno multi-sig y"))) ((("gobernanza"))) ((("direcciones multi-firma", "seguridad y"))) ((("gobernanza" seguridad " "))) (((" seguridad "," direcciones múltiples firmas y "))) Cuando una empresa o tiendas individuales tienen grandes cantidades de bitcoin, deberían considerar el uso de un dirección bitcoin multi-firma. Multi-firma se ocupa de mantener los fondos, al exigir más de una firma para hacer un pago. Las claves de firma deben ser almacenados en un número de diferentes ubicaciones y bajo el control de diferentes personas. En un entorno corporativo, por ejemplo, las claves deben ser generadas de forma independiente y en manos de varios ejecutivos de la empresa, para garantizar que ninguna persona sola puede comprometer los fondos. Direcciones Multi-firma también pueden ofrecer redundancia, donde una sola persona tiene varias claves que se almacenan en diferentes ubicaciones.

==== Supervivencia

((("Bitcoin", "la muerte del propietario y"))) ((("la muerte de los propietarios"))) ((("seguridad", "la muerte del propietario y"))) ((("seguridad", "supervivencia"))) ((("supervivencia"))) Una consideración importante de seguridad que a menudo se pasa por alto es la disponibilidad, especialmente en el contexto de incapacidad o muerte del titular de la clave. Los usuarios de Bitcoin se les dice que deben usar contraseñas complejas y mantener sus claves seguras y privadas, no compartir con nadie. Por desgracia, que la práctica hace que sea casi imposible para la familia del usuario recuperar los fondos si el usuario no está disponible para desbloquearlos. En la mayoría de los casos, de hecho, las familias de los usuarios de Bitcoin podría ser completamente conscientes de la existencia de los fondos de Bitcoin.

Si usted tiene un montón de bitcoin, usted debe considerar el intercambio de datos de acceso con un familiar o abogado de confianza. Un esquema de supervivencia más compleja se puede configurar con acceso multi-firma y administración patrimonial a través de un abogado especializado como un "ejecutor de activos digitales."

=== Conclusión

Bitcoin es algo completamente nuevo, sin precedentes, y de compleja tecnología. Con el tiempo vamos a desarrollar mejores herramientas y prácticas que son más fáciles de usar por los no expertos de seguridad. Por ahora, los usuarios de Bitcoin pueden utilizar muchos de los consejos discutidos aquí para disfrutar de una experiencia bitcoin seguro y sin problemas. (((Rango = "endofrange", startref = "ix_ch10-asciidoc2"))) (((rango = "endofrange ", startref =" ix_ch10-asciidoc1 "))) (((rango =" endofrange ", startref =" ix_ch10-asciidoc0 ")))
