[[ch9]]
== Cadenas alternativas, Monedas, pass:[<phrase role="keep-together">y Aplicaciones</phrase>] 

Bitcoin fue el resultado de 20 años de investigación en sistemas distribuidos y monedas y trajo una nueva tecnología revolucionaria en el espacio: el mecanismo de consenso descentralizado basado en la prueba de trabajo. Esta invención en el corazón del bitcoin, ha iniciado una ola de innovación en las monedas, los servicios financieros, la economía, los sistemas distribuidos, sistemas de votación, gobierno corporativo y contratos. 

En este capítulo vamos a examinar las muchas ramas del bitcoin e invenciones de la cadena de bloques: las cadenas alternativas, monedas y aplicaciones construidas desde la introducción de esta tecnología en el año 2009. En su mayoría, que se verá en monedas alternativas, o _alt coins_, que son monedas digitales implementadas utilizando el mismo patrón de diseño como bitcoin, pero con una cadena de bloques y una red completamente independiente. 

Por cada moneda alternativa mencionada en este capítulo, en 50 años o más dejará de mencionarse, provocando gritos de rabia de sus creadores y aficionados. El propósito de este capítulo no es evaluar o calificar monedas alternativas, o incluso mencionar las más significativas basadas ​​en alguna evaluación subjetiva. En su lugar, vamos a destacar algunos ejemplos que muestran la amplitud y variedad de los ecosistemas, tomando nota de la primera de su tipo para cada innovación o diferenciación significativa. Algunos de los ejemplos más interesantes de monedas alternativas son de hecho un completo fracaso desde el punto de vista monetario. Eso tal vez los hace aún más interesante para el estudio y destaca el hecho de que este capítulo no es para ser utilizado como una guía de inversión. 

Con nuevas monedas introducidas cada día, sería imposible no perderse algunas monedas importantes, tal vez el que cambia la historia. El ritmo de innovación es lo que hace de este espacio tan emocionante y garantiza este capítulo será incompleto y fuera de la fecha tan pronto como se publique.

=== Una Taxonomía de Monedas y Cadenas Alternativas

((("Cadenas, alternativa"))) ((("monedas, alternativa"))) Bitcoin es un proyecto de código abierto, y su código se ha utilizado como base para muchos otros proyectos de software. La forma más común de software generado a partir de código fuente del bitcoin son monedas alternativas descentralizadas, o _alt coins_, que utilizan los mismos bloques de construcción básicos para implementar las monedas digitales. 

Hay una serie de capas de protocolo implementado en la parte superior de la cadena de bloques de bitcoin. Estos ((("apps" blockchain))) ((("cadenas meta"))) ((("plataformas de monedas meta"))) _meta coins_, _meta chains_, o _blockchain apps_ utilizan la cadena de bloques como una plataforma de aplicaciones o ampliar el protocolo bitcoin mediante la adición de capas de protocolo. Los ejemplos incluyen monedas de colores, Mastercoin, NXT y de contraparte. 

En la siguiente sección vamos a examinar algunas monedas alternativas notables, como litecoin, dogecoin, Freicoin, Primecoin, peercoin, Darkcoin y Zerocoin. Estas monedas alternativas son notables por razones históricas o porque son buenos ejemplos de un tipo específico de la innovación de la moneda alternativa, no porque sean las más valiosas o "mejores" monedas alternativas. 

Además de las monedas alternativas, también hay una serie de implementaciones de la cadena de bloques alternativas que no son realmente "monedas", lo que yo llamo ((("cadenas alternativas"))) _alt chains_. Estas cadenas alternativas implementan un algoritmo de consenso y un libro mayor distribuido como una plataforma para los contratos, registro de nombres, u otras aplicaciones. Las cadenas alternativas utilizan los mismos bloques de construcción básicos y, a veces también usan una moneda o ficha como un mecanismo de pago, pero su objetivo principal no es moneda. Veremos Namecoin y Etereum como ejemplos de cadenas de alternativas. 

Por último, hay un número de aspirantes que ofrecen la moneda digital Bitcoin o redes de pago digitales, pero sin necesidad de utilizar un libro de contabilidad descentralizado o mecanismo de consenso basado en la prueba de trabajo, tales como Ripple y otros. Estas tecnologías no de cadena de bloques están fuera del alcance de este libro y no se tratan en este capítulo.

=== Plataformas Meta Moneda 

((("Plataformas de monedas meta", id = "ix_ch09-asciidoc0", rango = "startofrange"))) Las meta monedas y las cadenas meta son capas de software implementadas en la parte superior del bitcoin, ya sea la aplicación de moneda-dentro-de una-moneda, o una superposición de plataforma / protocolo dentro del sistema de Bitcoin. Estas capas de función extienden el núcleo del protocolo bitcoin y añaden características y capacidades mediante la codificación de datos adicionales dentro transacciones Bitcoin y de las direcciones Bitcoin. Las primeras implementaciones de monedas meta utilizaron varios cortes para añadir metadatos a la cadenade de bloques de bitcoin, tales como el uso de direcciones bitcoin para codificar datos o el uso de los campos no utilizados de transacción (por ejemplo, el campo de secuencia de la transacción) para codificar metadatos sobre la capa de protocolo añadido. Desde la introducción de la operación de transacción de scripting de código +OP_RETURN+, las monedas meta han sido capaces de registrar los metadatos de forma más directa en la cadena de bloques, y la mayoría están migrando a utilizarse en su lugar. 

==== Monedas Coloreadas

((("Monedas de colores"))) ((("plataformas de monedas meta", "monedas de colores"))) Las _monedas de colores_ es un meta protocolo que superpone información sobre pequeñas cantidades de bitcoin. Una moneda "de color" es una cantidad de bitcoin reutilizados para expresar otro activo. ((("Certificados de acciones", "monedas de colores como"))) Imagínese, por ejemplo, tomar un billete de $ 1, y poner un sello en él que decía: "Este es un certificado de 1 acción de Acme Inc." Ahora los $ 1 sirve para dos propósitos: se trata de una nota de la moneda y también un certificado de acciones. Debido a que es más valioso como una cuota, usted no quiere utilizarlo para comprar dulces, por lo que efectivamente ya no es útil como moneda. Las monedas de colores funcionan de la misma manera mediante la conversión de una muy pequeña cantidad específica, de bitcoin en un certificado de negociado que representa otro activo. El término "color" se refiere a la idea de dar un significado especial a través de la adición de un atributo como un color es una metáfora, no una asociación color real. No hay colores en las monedas de colores. 

((("Carteras", "para las monedas de color"))) Las monedas de colores son gestionadas por carteras especializadas que graban e interpretan los metadatos unidos a los bitcoins de colores. Usando una billetera tal, el usuario convierte una cantidad de bitcoins de moneda incoloro en monedas de color mediante la adición de una etiqueta que tiene un significado especial. Por ejemplo, una etiqueta podría representar certificados de acciones, cupones, bienes inmuebles, materias primas, o fichas coleccionables. Es totalmente de los usuarios de las monedas de colores para asignar e interpretar el significado del "color" asociado con las monedas específicas. Para colorear las monedas, el usuario define los metadatos asociados, tales como el tipo de emisión, si se puede subdividir en unidades más pequeñas, un símbolo y descripción, y otra información relacionada. Una vez coloreado, estas monedas pueden ser comprados y vendidos, subdivididos y agregados, y recibir pagos de dividendos. Las monedas de colores también pueden ser "sin color" mediante la eliminación de la asociación especial y canjeados por su valor nominal en bitcoin. 

Para demostrar el uso de monedas de colores, hemos creado un conjunto de 20 monedas de colores con el símbolo "MasterBTC" que representan cupones para una copia gratuita de este libro se muestra en la <<example_9-1>>. Cada unidad de MasterBTC, representada por estas monedas de color, ahora se puede vender o dar a cualquier usuario bitcoin con una cartera de color-coin-competente, que luego los puede transferir a otros o canjearlos con el emisor para obtener una copia gratuita del libro . Este ejemplo de monedas de colores puede verse https://cpr.sm/FoykwrH6UY[here].

[[example_9-1]]
.El perfil de metadatos de las monedas coloreadas registrado como un cupón para una copia gratuita de un libro
====
[source,json]
----
{
  "source_addresses": [
    "3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD"
  ],
  "contract_url": "https://www.coinprism.info/asset/3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD",
  "name_short": "MasterBTC",
  "name": "Free copy of \"Mastering Bitcoin\"",
  "issuer": "Andreas M. Antonopoulos",
  "description": "This token is redeemable for a free copy of the book \"Mastering Bitcoin\"",
  "description_mime": "text/x-markdown; charset=UTF-8",
  "type": "Other",
  "divisibility": 0,
  "link_to_website": false,
  "icon_url": null,
  "image_url": null,
  "version": "1.0"
}
----
====

==== Mastercoin

((("Plataformas meta-moneda", "Protocolo mastercoin"))) Mastercoin es una capa de protocolo en la parte superior de bitcoin que soporta una plataforma para diversas aplicaciones que se extienden al sistema Bitcoin. Mastercoin utiliza la moneda MST como una muestra para realizar transacciones Mastercoin pero no es principalmente una moneda. Más bien, es una plataforma para la construcción de otras cosas, tales como monedas de usuario, fichas de propiedad inteligentes, intercambios descentralizados de activos y contratos. Piense en Mastercoin como un protocolo de capa de aplicación en la parte superior de la capa de transporte a las transacciones financieras del bitcoin, como HTTP se ejecuta sobre TCP. 

Mastercoin opera principalmente a través de transacciones enviadas hacia y desde una dirección bitcoin especial llamada la ((("direcciones éxodo"))) dirección "éxodo" (+1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P+), al igual que HTTP utiliza un puerto TCP específico (puerto 80) para diferenciar su tráfico desde el resto del tráfico TCP. El protocolo Mastercoin está en la transición gradual del uso de la dirección de éxodo especializado y múltiples firmas de utilizar el operador bitcoin OP_RETURN para codificar metadatos transacción.

==== Contraparte

((("Plataformas de monedas meta", "protocolo contraparte"))) Contraparte es otra capa de protocolo implementado en la parte superior de bitcoin. Contraparte permite monedas de usuario, fichas negociables, instrumentos financieros, los intercambios de activos descentralizados, y otras características. Contraparte se implementa utilizando principalmente el operador +OP_RETURN+ en el lenguaje de scripting de bitcoin para grabar metadatos que mejoren transacciones Bitcoin con significado adicional. Contraparte utiliza el símbolo XCP como moneda para la realización de transacciones de contrapartida. (((Rango = "endofrange", startref = "ix_ch09-asciidoc0"))) 

=== Monedas Alternativas 

((("Monedas alt", id = "ix_ch09-asciidoc1", rango = "startofrange"))) ((("monedas, alternativo", id = "ix_ch09-asciidoc2", rango = "startofrange"))) La gran mayoría de monedas alternativas se derivan de código fuente de bitcoin, también conocido como "horquillas". Algunas se implementan "desde cero", basada en el modelo de caldena de bloques pero sin utilizar ningún de código fuente de bitcoin. Monedas Alt y cadenas alt (en la siguiente sección) son dos implementaciones independientes de la tecnología de la cadena de bloques y ambas formas utilizan su propio cadena de bloques. La diferencia en los términos es para indicar que las monedas alt se utilizan principalmente como moneda, mientras que las cadenas alt se utilizan para otros fines, no principalmente de divisas. 

Estrictamente hablando, la primera gran horquilla "alt" del código de bitcoin no era una moneda alt pero la cadena alt _Namecoin_, que vamos a discutir en la próxima sección. 

Sobre la base de la fecha del anuncio, la primera moneda alt que era una horquilla de bitcoin apareció en agosto de 2011; se llamaba _IXCoin_. IXCoin modifica algunos de los parámetros bitcoin, acelerando específicamente la creación de moneda mediante el aumento de la recompensa a 96 monedas por bloque.

En septiembre de 2011, se puso en marcha _Tenebrix_. Tenebrix fue la primera criptomoneda en implementar un algoritmo alternativo de prueba de trabajo, llamado ((("algoritmo de prueba de trabajo", "alternativa"))) ((()) "algoritmo scrypt") _scrypt_, un algoritmo original diseñado para una extensión de la contraseña (resistencia-fuerza bruta). El objetivo declarado de Tenebrix era hacer una moneda que fuera resistente a la minería con las GPU y ASIC, mediante el uso de un algoritmo de mucha memoria. Tenebrix no tuvo éxito como moneda, pero fue la base para litecoin, que ha gozado de gran éxito y ha generado cientos de clones. 

_Litecoin_, Además de utilizar scrypt como el algoritmo de prueba de trabajo, también implementó un tiempo más rápido bloque de generación, dirigida a los 2,5 minutos en lugar de 10 minutos de Bitcoin. La moneda resultante se promociona como "la plata al oro de bitcoin" y pretende ser una moneda alternativa de peso ligero. Debido al tiempo de confirmación más rápido y el límite total de divisas de 84 millones, muchos partidarios de litecoin creen que es más adecuado para las transacciones comerciales que bitcoin. 

Las monedas Alt continuaron proliferando en 2011 y 2012, ya sea basadas en bitcoin o en Litecoin. En 2013, había 20 monedas alt que compiten por la posición en el mercado. A finales de 2013, este número había explotado a 200, en 2013 se convirtió rápidamente en el "año de las monedas de alt." El crecimiento de las monedas alt continuó en 2014, con más de 500 alt monedas en existencia en el momento de la escritura. Más de la mitad de las monedas alt hoy son clones de litecoin. 

La creación de una moneda alt es fácil, por lo que ahora hay más de 500 de ellos. La mayor parte de las monedas alt difieren muy ligeramente de bitcoin y no ofrecen nada digno de estudio. Muchos de ellos son de hecho, sólo intenta enriquecer sus creadores. Entre los imitadores y los planes de la bomba-and-dump, hay sin embargo, algunas excepciones notables e innovaciones muy importantes. Estas monedas alt toman radicalmente diferentes enfoques o añaden innovación significativa al patrón de diseño de bitcoin. Hay tres áreas principales donde estas monedas alt se diferencian de bitcoin:

* Distinta política monetaria
* Distinto mecanismo de prueba de trabajo o consenso
* Características específicas, como anonimato fuerte

Para obtener más información, consulte este http://mapofcoins.com [cronología gráfica de monedas alt y cadenas alt]. ((("Cadenas alt", "línea de tiempo de"))) ((("monedas alt", "línea de tiempo de ")))

==== Evaluando una Moneda Alternativa

((("Monedas alt", "la evaluación"))) ((("monedas, alternativo", "la evaluación"))) Con tantas monedas alt por ahí, ¿cómo decidir cuáles son dignas de atención? Algunas monedas alt intentan lograr una amplia distribución y su uso como monedas. Otros son laboratorios para experimentar con diferentes características y modelos monetarios. Muchos son los planes simplemente para hacerse rico rápido por parte de sus creadores. Para evaluar las monedas alt, miro sus características definitorias y sus métricas de mercado.

Aquí hay algunas preguntas acerca de qué tan bien una moneda alternativa se diferencia de bitcoin:

* ¿La moneda alternativa presenta una innovación significativa?
* ¿Es la diferencia suficientemente persuasiva como para atraer usuarios de bitcoin?
* ¿La moneda alternativa apunta a un nicho de mercado o aplicación interesante?
* ¿Puede la moneda alternativa atraer suficientes mineros para estar segura contra ataques de consenso?

Aquí hay algunas de las diferencias financieras clave y métricas de mercado a considerar:

* ¿Cuál es la capitalización de mercado total de la moneda alternativa?
* ¿Cuántos usuarios/carteras estimados tiene la moneda alternativa?
* ¿Cuántos comerciantes aceptan la moneda alternativa?
* ¿Cuántas transacciones diarias (volumen) son ejecutadas en la moneda alternativa?
* ¿Cuánto valor es movido diariamente?

En este capítulo nos concentraremos principalmente en las características técnicas y potencial de innovación de las monedas alternativas representadas por el primer juego de preguntas.

=== Parámetros Monetarios Alternativos: Litecoin, Dogecoin, Freicoin

((("Monedas alt", "alternativas parámetros monetaria"))) ((("monedas, alternativo", "alternativas parámetros monetaria"))) ((("alternativas parámetros monetarios"))) Bitcoin tiene algunos parámetros monetarios que le dan características distintivas de una moneda-emisión fijo deflacionaria. Está limitado a 21 millones de unidades divisas principales (o 21 billones de unidades menores), que tiene una tasa de emisión geométricamente en declive, y tiene un bloque de 10 minutos de "latido", que controla la velocidad de la confirmación de la transacción y la generación de divisas. Muchas monedas alt han ajustado los parámetros principales para lograr diferentes políticas monetarias. Entre los cientos de monedas alt, algunos de los ejemplos más notables incluyen lo siguiente.

===== Litecoin

Una de las primeras monedas alt, lanzada en 2011, Litecoin es la segunda moneda digital más exitosa después bitcoin. Sus innovaciones principales fueron el uso de _scrypt_ como el algoritmo de prueba de trabajo (heredado de Tenebrix) y sus rápidos / ligeros parámetros de divisas.

* Tiempo de generación de bloque: 2,5 minutos
* Moneda total: 84 millones de monedas hacia 2140
* Algoritmo de consenso: Prueba de trabajo Scrypt
* Capitalización de mercado: $160 millones a mediados de 2014

===== Dogecoin

Dogecoin fue lanzado en diciembre de 2013, sobre la base de un bifrucación de litecoin. Dogecoin es notable, ya que tiene una política monetaria de emisión rápida y una cima de moneda muy alta, para fomentar el gasto y el depósito. Dogecoin también es notable, ya que se inició como una broma, pero se hizo muy popular, con una comunidad grande y activa, antes de disminuir rápidamente en 2014. 

* Tiempo de generación de bloque: 60 segundos
* Moneda total: 100.000.000.000 (100 mil millones) de Doges hacia 2015
* Algoritmo de consenso: Prueba de trabajo Scrypt
* Capitalización de mercado: $12 millones a mediados de 2014

===== Freicoin

Freicoin se introdujo en julio de 2012. Se trata de una ((("moneda estadía"))) _demurrage currency_, lo que significa que tiene un tipo de interés negativo para el valor almacenado. Valor almacenado en Freicoin se evalúa una cuota abril un 4,5%, para fomentar el consumo y desalentar el acaparamiento de dinero. Freicoin es notable en que implementa una política monetaria que es exactamente lo contrario de la política deflacionista de Bitcoin. Freicoin no ha visto el éxito como una moneda, pero es un interesante ejemplo de la variedad de las políticas monetarias que se pueden expresar por monedas de alt.

* Generación de bloque: 10 minutos
* Moneda total: 100 millones de monedas hacia 2140
* Algoritmo de consenso: Prueba de trabajo SHA256
* Capitalización de mercado: $130.000 a mediados de 2014

==== Innovación de Consenso: Peercoin, Myriad, Blackcoin, Vericoin, NXT

((("Monedas alt", "innovación consenso"))) ((("consenso", "innovación"))) Los mecanismos de consenso de Bitcoin se basan en la prueba de trabajo utilizando el algoritmo SHA256. Las primeras monedas introducidas alt scrypt como un algoritmo alternativo de prueba de trabajo, como una forma de hacer minería más CPU amable y menos susceptibles a la centralización con ASICs. Desde entonces, la innovación en el mecanismo de consenso ha continuado a un ritmo frenético. Varias monedas alt adoptaron una variedad de algoritmos como scrypt, ((("Blake algoritmo"))) ((("algoritmo Groestl"))) ("algoritmo scrypt-N" (())) ((("algoritmo SHA3 "))) (((" algoritmo Madeja "))) scrypt-N, Madeja, Groestl, SHA3, X11, Blake, y otros. Algunas monedas alt combinan múltiples algoritmos para la prueba de trabajo. En 2013, vimos la invención de una alternativa a la prueba de trabajo, llamado ((("prueba de la participación"))) _proof de stake_, que forma la base de muchas monedas alt modernos. 

La prueba de la participación es un sistema por el cual los propietarios existentes de una moneda puede poner en "juego" la moneda como garantía que devenga intereses. Algo así como un certificado de depósito (CD), los participantes pueden reservar una parte de sus reservas de divisas, al mismo tiempo ganar un retorno de inversión en forma de nueva moneda (publicado como el pago de intereses) y las comisiones por transacciones. 

===== Peercoin

Peercoin se introdujo en agosto de 2012 y es la primera moneda alt en utilizar un algoritmo híbrido de prueba de trabajo y prueba de juego para emitir nueva moneda. 

* Generación de bloque: 10 minutos
* Total de moneda: Sin límite
* Algoritmo de consenso: (Híbrido) prueba de participación con prueba de trabajo inicial
Capitalización de mercado: $14 millones a mediados de 2014

===== Myriad

Myriad se introdujo en febrero de 2014 y es notable, ya que utiliza cinco diferentes algoritmos de prueba de trabajo (SHA256d, Scrypt, Qubit, Madeja, o Myriad-Groestl) simultáneamente, con dificultad variable para cada algoritmo en función de la participación de la minera. La intención es hacer Myriad inmune a ASIC especialización y centralización, así como mucho más resistentes a los ataques de consenso, porque múltiples algoritmos de minería tendrían que ser atacado simultáneamente.

* Bloquear generación: 30 segundos promedio (2,5 minutos por objetivo algoritmo de minería)
* Moneda total: 2 mil millones hacia 2024
* Algoritmo de consenso: Prueba de trabajo multi-algorítimica
* Capitalización de mercado: $120.000 a mediados de 2014

===== Blackcoin

Blackcoin se introdujo en febrero de 2014 y utiliza un algoritmo de consenso de prueba de juego. También es notable por introducir "MultiPools", un tipo de pools de minería que puede cambiar entre diferentes monedas alt automáticamente, en función de la rentabilidad. 

* Generación de bloque: 1 minuto
* Total de moneda: Sin límite
* Algoritmo de consenso: Prueba de participación
* Capitalización de mercado: $3,7 millones a mediados de 2014

===== VeriCoin

VeriCoin fue lanzado en mayo de 2014. Se utiliza un algoritmo de consenso de prueba de juego con una tasa de interés variable que se ajusta dinámicamente basada en las fuerzas del mercado de la oferta y la demanda. También es la primera que ofrece la moneda alt-intercambio automático de Bitcoin para el pago en bitcoin de la cartera.

* Generación de bloque: 1 minuto
* Total de moneda: Sin límite
* Algoritmo de consenso: Prueba de participación
* Capitalización de mercado: $1,1 millones a mediados de 2014

===== NXT

NXT (pronunciado "Siguiente") es una moneda alt "pura" de prueba de juego, ya que no utiliza la minería de prueba de trabajo. NXT es una implementación de una criptomoneda desde cero , no una bifurcación de bitcoin o cualquier otro monedas alt. NXT implementa muchas características avanzadas, incluyendo un registro de nombres (similar a ((("Namecoin"))) Namecoin), un intercambio descentralizado de activos (similar a monedas de colores), mensajería descentralizada y seguro integrado (similar a ((("Bitmessage" ))) Bitmessage), y la delegación de participación (a delegar prueba de juego para los demás). Adherentes NXT llaman una "próxima generación" o criptomoneda 2.0. 

* Generación de bloque: 1 minuto
* Total de moneda: Sin límite
* Algoritmo de consenso: Prueba de participación
* Capitalización de mercado: $30 millones a mediados de 2014


==== Innovación en Minado de Doble Propósito: Primecoin, Curecoin, Gridcoin

((("Minería de doble propósito"))) ((("minería", "doble propósito"))) el algoritmo de Bitcoin prueba de trabajo tiene un solo propósito: asegurar la red Bitcoin. En comparación con la seguridad del sistema de pago tradicional, el costo de la minería no es muy alto. Sin embargo, ha sido criticado por muchos como "un desperdicio." La próxima generación de monedas alt intenta abordar esta preocupación. De doble propósito de prueba de trabajo de algoritmos de resolver un problema "útil" específico, mientras que producen prueba de trabajo para asegurar la red. El riesgo de la adición de un uso externo para la seguridad de la moneda es que también añade influencia externa a la curva de oferta / demanda. 

===== Primecoin

Primecoin se anunció en julio de 2013. Sus búsquedas de prueba de trabajo se basan en algoritmo de números primos, informática ((("cadenas principales bi-gemelas"))) ((("Cunningham principales cadenas"))) Cunningham y cadenas de primos bi-doble. Los números primos son útiles en una variedad de disciplinas científicas. La cadena de bloques de Primecoin contiene los números primos descubiertos, produciendo de esta manera un registro público de los descubrimientos científicos en paralelo a la contabilidad pública de las transacciones. 

* Generación de bloque: 1 minuto
* Total de moneda: Sin límite
* Algoritmo de consenso: Prueba de trabajo con descubrimiento de cadena de números primos
* Capitalización de mercado: $1,3 millones a mediados de 2014

===== Curecoin

((("algoritmos de plegamiento de proteínas"))) Curecoin fue anunciado en mayo de 2013. Combina un algoritmo SHA256 de prueba de trabajo con la investigación de plegamiento de proteínas a través del proyecto Folding@Home. El plegamiento de proteínas es una simulación de cómputo intensivo de las interacciones bioquímicas de las proteínas, que se utiliza para descubrir nuevas objetivos de medicamentos para curar enfermedades. 

* Generación de bloque: 10 minutos
* Total de moneda: Sin límite
* Algoritmo de consenso: Prueba de trabajo con investigación de plegamiento de proteínas
* Capitalización de mercado: $58.000 a mediados de 2014

===== Gridcoin

Gridcoin se introdujo en octubre de 2013. Complementa la prueba de trabajo basada en scrypt basado en las subvenciones para la participación abierta en ((("BOINC grid computing abierta"))) de BOINC grid computing. BOINC-Infraestructura Abierta para la Computación en Red de Berkeley- es un protocolo abierto para científicos de investigación de computación en red, que permite a los participantes compartir sus ciclos de cómputo de piezas para una amplia gama de computación en la investigación académica. Gridcoin utiliza BOINC como una plataforma de computación de propósito general, en lugar de resolver los problemas específicos de la ciencia, como los números primos o plegamiento de proteínas. 

* Generación de bloque: 150 segundos
* Total de moneda: Sin límite
* Algoritmo de Consenso: La prueba de trabajo con subsidioen la red  BOINC computing
* Capitalización de mercado: $122.000 a mediados de 2014

==== Anonimato-Centrado Alt Monedas: CryptoNote, Bytecoin, Monero, Zerocash / Zerocoin, Darkcoin

((("Monedas alt", "anonimato enfocados", id = "ix_ch09-asciidoc3", rango = "startofrange"))) ((("monedas, alternativo", "anonimato enfocados", id = "ix_ch09-asciidoc4" , rango = "startofrange"))) Bitcoin es a menudo erróneamente caracterizado como moneda "anónima". De hecho, es relativamente fácil de conectar identidades de direcciones Bitcoin y, usando análisis de datos grande, conecta direcciones entre sí para formar una imagen completa de los hábitos de consumo de bitcoin de alguien. Varias monedas alt apuntan a tratar este tema directamente al centrarse en un fuerte anonimato. El primer intento de este tipo y el más probable es _Zerocoin_, un protocolo de meta-moneda para preservar el anonimato en la parte superior del bitcoin, introducida con un papel en el 2013 IEEE Simposio sobre Seguridad y Privacidad. Zerocoin será implementado como una moneda alt completamente separada llamada Zerocash, en el desarrollo en el momento de la escritura. Un enfoque alternativo al anonimato fue lanzado con _CryptoNote_ en un artículo publicado en octubre de 2013. CryptoNote es una tecnología fundamental que se implementa por un número de bifurcaciones de monedas alt discutidos a continuación. Además de Zerocash y CryptoNotes, hay varias otras monedas anónimas independientes, tales como Darkcoin, que utilizan direcciones de sigilo o transacción re-mezcla para entregar el anonimato.

===== Zerocoin/Zerocash

Zerocoin es una aproximación teórica al anonimato de moneda digital introducida en 2013 por investigadores de la Johns Hopkins. Zerocash es una implementación de alt-moneda Zerocoin que está en desarrollo y aún no depurada. 

===== CryptoNote

CryptoNote es una implementación de moneda alt de referencia que proporciona la base para el dinero digital anónimo. Fue introducido en octubre de 2013. Está diseñado para ser bifurcado en diferentes implementaciones y tiene incorporado un mecanismo de reposición periódica que hace inutilizable como moneda propia. Varias monedas alt se han generado a partir de CryptoNote, incluyendo Bytecoin (BCN), Aeon (AEON), Boolberry (BBR), duckNote (PATO), Fantomcoin (FCN), Monero (XMR), MonetaVerde (MCN) y Quazarcoin (QCN) . CryptoNote también es notable por ser una aplicación primera capa superior completa de una moneda de cifrado, no es una bifurcación de bitcoin. 

===== Bytecoin

((("Application Specific Integrated Circuit (ASIC)"))) ((("unidades de procesamiento gráfico (GPU)"))) Bytecoin fue la primera aplicación generada a partir de CryptoNote, ofreciendo una moneda anónima viable basado en la tecnología CryptoNote. Bytecoin fue lanzado en julio de 2012. Tenga en cuenta que no era una moneda alt anterior llamado Bytecoin con símbolo de moneda BTE, mientras que el Bytecoin derivados de CryptoNote tiene el símbolo de moneda BCN. Bytecoin utiliza el algoritmo Cryptonight prueba de trabajo, que requiere el acceso a por lo menos 2 MB de RAM por ejemplo, por lo que es inadecuado para la GPU o la minería ASIC. Bytecoin firmas hereda anillo, transacciones unlinkable y análisis resistente blockchain anonimato de CryptoNote.

* Generación de bloque: 2 minutos
* Moneda total: 184 mil millones de BCN
* Algoritmo de consenso: Prueba de trabajo Cryptonight
* Capitalización de mercado: $3 millones a mediados de 2014

===== Monero

Monero es otra implementación de CryptoNote. Tiene una curva de emisión ligeramente más plana que Bytecoin, la emisión de 80% de la moneda en los primeros cuatro años. Ofrece las mismas características de anonimato heredados de CryptoNote.

* Generación de bloque: 1 minuto
* Moneda total: 18,4 millones de XMR
* Algoritmo de consenso: Prueba de trabajo Cryptonight
* Capitalización de mercado: $5 millones a mediados de 2014

===== Darkcoin

Darkcoin se puso en marcha en enero de 2014. Darkcoin implementa moneda anónima utilizando un protocolo de re-mezcla de todas las transacciones denominadas DarkSend. Darkcoin también es notable por el uso de 11 rondas de diferentes funciones hash ((("algoritmo de prueba de trabajo", "para Darkcoin"))) (blake, bmw, groestl, jh, keccak, madeja, luffa, cubehash, shavite, SIMD, eco) para el algoritmo de prueba de trabajo.

* Generación de bloque: 2,5 minutos
* Moneda total: Máximo de 22 millones de DRK
* Algoritmo de consenso: la prueba de varias rondas de múltiples algoritmo de trabajo
* La capitalización de mercado: $ 19 millones a mediados de 2014(((range="endofrange", startref="ix_ch09-asciidoc4")))(((range="endofrange", startref="ix_ch09-asciidoc3")))(((range="endofrange", startref="ix_ch09-asciidoc2")))(((range="endofrange", startref="ix_ch09-asciidoc1")))

=== Cadenas Alternativas no Monetarias

((("Cadenas, alternativo", "noncurrency", id = "ix_ch09-asciidoc5", rango = "startofrange"))) ((("no-monetarias cadenas alt", id = "ix_ch09-asciidoc6", rango = "startofrange"))) Las cadenas Alt son implementaciones alternativas del patrón de diseño de la cadena de bloques, que no se utilizan principalmente como moneda. Muchos incluyen una moneda, pero la moneda se utiliza como muestra para la asignación de alguna otra cosa, como un recurso o un contrato. La moneda, en otras palabras, no es el punto principal de la plataforma; es una característica secundaria.  

==== Namecoin

Namecoin fue la primera bifurcación del código bitcoin. Namecoin es una clave-valor de registro y plataforma de transferencia descentralizada mediante una cadena de bloques. Es compatible con un registro de nombre de dominio mundial similar al sistema de registro de nombres de dominio en Internet. Namecoin se utiliza actualmente como una alternativa ((("servicio de nombres de dominio (DNS)"))) servicio de nombres de dominio (DNS) para el dominio de nivel raíz +.bit+. Namecoin también se puede utilizar para registrar nombres y pares clave-valor en otros espacios de nombres; para almacenar cosas como direcciones de correo electrónico, claves de cifrado, certificados SSL, firmas de archivos, sistemas de votación, certificados de acciones; y una multitud de otras aplicaciones. 

El sistema Namecoin incluye la moneda Namecoin (símbolo NMC), que se utiliza para pagar los honorarios de transacción para el registro y la transferencia de nombres. A los precios actuales, la cuota de registrar un nombre es de 0,01 NMC o aproximadamente 1 centavo de dólar. Al igual que en bitcoin, los honorarios son recogidos por los mineros namecoin.

Los parámetros básicos de Namecoin son los mismos que en bitcoin:  

* Generación de bloque: 10 minutos
* Moneda total: 21 millones de NMC hacia 2140
* Algoritmo de consenso: Prueba de trabajo SHA256
* Capitalización de mercado: $10 millones a mediados de 2014

Los espacios de nombres de Namecoin no están restringidos, y cualquier persona puede utilizar cualquier espacio de nombres de cualquier manera. Sin embargo, ciertos espacios de nombres tienen acordado una especificación para que cuando se lean desde la cadena de bloques, el software de nivel de aplicación sepa leer y proceder desde allí. Si está mal formado, entonces cualquier software que utilizó para leer desde el espacio de nombres específico lanzará un error. Algunos de los espacios de nombres populares son:

* +d/+ es el nombre de dominio del espacio de nombres de dominios +.bit+
* +id/+ es el espacio de nombres para almacenar personas identificadas tales como direcciones de correo electrónico, claves PGP, etc.
* +u/+ es una especificación adicional, más estructurada para almacenar identidades (basado en openspecs)

((("Blockchains", "Namecoin"))) El cliente Namecoin es muy similar a Bitcoin Core, porque se deriva desde el mismo código fuente. Tras la instalación, el cliente descarga una copia completa de la cadena de bloques Namecoin y luego estará listo para consultar y registrar nombres. Hay tres comandos principales: ((("Namecoin", "comandos"))) 

+name_new+:: Consulta o pre-registra un nombre
+name_firstupdate+:: Registra un nombre y hace público el registro
+name_update+:: Cambia los detalles o actualiza un registro de nombre

Por ejemplo, para registrar el dominio +dominio-bitcoin.bit+, utilizamos el comando +name_new+ de la siguiente manera:

[source,bash]
----
$ namecoind name_new d/mastering-bitcoin
----
[source,json]
----
[
    "21cbab5b1241c6d1a6ad70a2416b3124eb883ac38e423e5ff591d1968eb6664a",
    "a05555e0fc56c023"
]
----

El comando +name_new+ registra una reclamación en el nombre, mediante la creación de un hash del nombre con una clave aleatoria. Las dos cadenas devueltas por +name_new+ son el hash y la clave aleatoria (+a05555e0fc56c023+ en el ejemplo anterior) que se puede utilizar para hacer un registro público de nombres. Una vez que la reclamación ha sido registrado en la cadena de bloques de Namecoin  se puede convertir en un registro público con el comando +name_firstupdate+, proporcionando la clave aleatoria:

----
$ namecoind name_firstupdate d/mastering-bitcoin a05555e0fc56c023 "{"map": {"www": {"ip":"1.2.3.4"}}}}"
b7a2e59c0a26e5e2664948946ebeca1260985c2f616ba579e6bc7f35ec234b01
----

En este ejemplo se asignará el nombre de dominio +www.mastering-bitcoin.bit+ a la dirección IP 1.2.3.4. El hash devuelto es el ID de la transacción que se puede utilizar para realizar un seguimiento de este registro. Usted puede ver qué nombres están registrados ejecutando el del comando +NAME_LIST+:

----
$ namecoind name_list
----
====
[source,json]
----
[
    {
        "name" : "d/mastering-bitcoin",
        "value" : "{map: {www: {ip:1.2.3.4}}}}",
        "address" : "NCccBXrRUahAGrisBA1BLPWQfSrups8Geh",
        "expires_in" : 35929
    }
]
----
====

Los registros Namecoin necesitan ser actualizados cada 36 000 bloques (aproximadamente de 200 a 250 días). El comando +name_update+ no tiene ningún cargo y por lo tanto la renovación de dominios en Namecoin es gratuito. Proveedores de terceros pueden manejar el registro, renovación automática, y la actualización a través de una interfaz web, por un módico precio. Con un proveedor de terceros puede evitar la necesidad de ejecutar un cliente Namecoin, pero se pierde el control independiente de un registro de nombres descentralizado ofrecido por Namecoin. 

==== Ethereum

((("contratos, en Etereum"))) Etereum es una plataforma de procesamiento de contratos y ejecución de Turing-completo basado en un libro de contabilidad de cadena de bloques. No es un clon de Bitcoin, pero tiene un diseño e implementación completamente independiente. Etereum tiene incorporada la moneda, llamada _ether_, que se requiere con el fin de pagar por la ejecución del contrato. Los registros de Etereum en la cadena de bloques son los _contracts_, que se expresan en un nivel bajo, byte-código como, lenguaje Turing-completo. En esencia, un contrato es un programa que se ejecuta en cada nodo en el sistema Etereum. Los contratos Etereum pueden almacenar datos, enviar y recibir pagos de éter, almacenar ether, y ejecutar una gama infinita (de ahí Turing-completo) de las acciones computables, actuando como agentes de software autónomos descentralizados.

Ethereum puede implementar sistemas muy complejos que se implementan también como propias cadenas alt. Por ejemplo, el siguiente es un contrato Namecoin-como el registro de nombres escritos en Ethereum (o más exactamente, escrito en un lenguaje de alto nivel que puede ser compilado a código Etereum): (((rango = "endofrange", startref = "ix_ch09 -asciidoc6 "))) (((rango =" endofrange ", startref =" ix_ch09-asciidoc5 ")))

[source,python]
----
if !contract.storage[msg.data[0]]: # ¿Ya está tomada la clave?
    # ¡Entonces la tomamos!
    contract.storage[msg.data[0]] = msg.data[1]
    return(1)
else:

    return(0) // De lo contrario no hacer nada
----

=== Futuro de las Monedas

El futuro de las monedas criptográficas en general es aún más brillante que el futuro de bitcoin. Bitcoin introdujo una nueva forma de organización y consenso descentralizado que ha generado cientos de innovaciones increíbles. Estas invenciones probablemente afectarán a amplios sectores de la economía, desde la ciencia de los sistemas distribuidos hasta las finanzas, economía, monedas, banca central, y la gobernanza corporativa. Muchas actividades humanas que anteriormente requerían instituciones u organizaciones centralizadas para funcionar como autoridad o puntos de control de confianza ahora pueden descentralizarse. La invención de la cadena de bloques (blockchain) y el sistema de consenso reducirá significativamente el costo de organización y coordinación de los sistemas a gran escala, mientras que elimina las oportunidades para la concentración de poder, la corrupción, y la captura del regulador. 