[[ch10]]
== Bitcoinの安全性

((("security", id="ix_ch10-asciidoc0", range="startofrange")))Bitcoinは、銀行口座の残高のように金額が要約されたもの（？？）ではないため、安全性を保つことは大変です。「実際に持っている者が９割方勝つ」（？？）という言い回しを聞いたことがあるかもしれませんが、Bitcoinでは実際に持っている者が１０割方勝ちます。Bitcoinの鍵を持っていることは、現金や貴金属の塊を持っていることと同じです。無くすことも、置き忘れることも、盗まれることも、誰かに誤った量を渡してしまうこともあります。これらのどのケースでも、歩道に現金を落としてしまったときと同様に、ユーザーはBitcoinを使うことができなくなります。 

しかしながら、Bitcoinは、現金や金や銀行口座にはできないことができます。鍵が納められたBitcoinウォレットは、ファイルのようにバックアップが可能です。いくつもコピーを作って保存できますし、バックアップとして紙に印刷することもできます。現金や金や銀行口座は、「バックアップ」することはできません。Bitcoinは既存のどのようなものとも異なるので、私たちはBitcoinの安全性について考える時も、今までにない新しい方法で行う必要があります。 

=== 安全性の原則

((("security","principles of")))Bitcoinの重要な原則は分散化であり、このことはBitcoinの安全性について重要なインプリケーションを導きます。伝統的な銀行や支払ネットワークのような集中化モデルは、アクセス制限と審査によって、悪意のある主体をシステムから遠ざけます。一方、Bitcoinのような分散化システムは、責任と管理権をユーザーに付与します。ネットワークの安全性はproof of workに基づくものであってアクセス制限によるものではないため、ネットワークはオープンであり、Bitcoinのトラフィックに暗号化は必要ありません。 

クレジットカードのような伝統的な支払ネットワークでは、((("credit card payment system")))((("payment networks, traditional"))) ユーザーのプライベートな識別情報（クレジットカード番号）を含んでいるので、支払いは無制限（？？）です。最初に課金してからも、その識別情報にアクセスできる者であれば、何度でもユーザーに課金してお金を「引き出す」ことができます。したがって支払ネットワークは、暗号化により徹底的に（？？）保護されなければなりませんし、支払いのトラフィックが、プロセスの途中であれ（安全に）保存された状態であれ、((("eavesdroppers")))盗聴者や媒介者により漏洩され得ないことを保証しなければいけません。もし、悪意のある主体がシステムにアクセスできたら、現在のトランザクションと支払トークンの両方を手に入れ、これらを用いて新たなトランザクションを作り出すことが可能になります。さらに悪いことに、顧客情報が漏洩した場合には、その顧客はなりすましにさらされ、アカウントの不正使用を防ぐために行動を起こさなければならなくなります。

Bitcoinは全く異なります。Bitcoinのトランザクションは、特定の受取人に対する特定の金額（？）のみを承認するものであって、捏造されることも変更されることもありません。また、取引主体を特定するようなどんなプライベート情報も明かしませんし、追加的に別の支払いの承認に用いることもできません。従って、Bitcoinの支払ネットワークには、暗号化も盗聴者からの保護も必要ありません。実際、ユーザーは、厳格に保護されてはいない、WiFiやBluetoothといったオープンな公共チャネルを通じて、安全性を失うことなくトランザクションをブロードキャストできます。

Bitcoinの分散化された安全性モデルは、ユーザーの手に強い力を授けますが、その力は、鍵の秘匿性の維持に対する責任とともに与えられるものです。ほとんどのユーザーにとって、鍵の秘匿性の維持は簡単なことではありません。インターネットに接続したスマートフォンやPCといった、一般的な用途のコンピュータデバイスでは、特にそうです。Bitcoinの分散化モデルはクレジットカードで起こるような大規模な漏洩は防げるものの、多くのユーザーは鍵を適切に保護できておらず、ひとつずつハックされています。


==== Bitcoinのシステムを安全に開発する

((("bitcoin","system security")))((("security","centralized controls and")))Bitcoin関連のソフトウェア開発者にとって、最も重要な原則は分散化です。ほとんどの開発者は集中化された安全性モデルに慣れており、開発しているBitcoinアプリケーションにこのモデルを適用する誘惑に駆られることでしょうが、それは悲惨な結果を生むことになります。 

Bitcoinの安全性は、鍵の分散管理と、マイナーによる独立したトランザクション認証に基づいています。Bitcoinならではの安全性を活用したいのであれば、Bitcoinの安全性モデルの考え方から離れないでいる必要があります。つまり、鍵の管理はユーザーに任せよ、トランザクションはブロックチェーンに任せよ、ということです。 

たとえば、初期のBitcoin交換所は、すべてのユーザーの資金をひとつの「ホットな」ウォレットに集め、鍵とともにひとつのサーバーに保存しました。こうした設計は、ユーザーから鍵の管理を取り上げ、単一のシステムに集約するものです。こうした多くのシステムはハックされ、顧客にとって悲惨な結果を招いています。 

((("transactions","taking off blockchain")))よくあるもうひとつの誤りは、トランザクション手数料を削減するため、またはトランザクションの処理プロセスを早めるための間違った努力のうちに、「ブロックチェーン外」でトランザクションを作ることです。「ブロックチェーン外」システムは、内部の集中化された元帳にトランザクションを記録し、Bitcoinのブロックチェーンとたまに同期するといったものです。こうした実践もまた、分散化されたBitcoinの安全性を、独占され集中化されたアプローチで代替するものです。トランザクションがブロックチェーンの外で作られると、適切に保護されていない集中化された元帳は改竄される可能性があり、その場合、気づかれないうちに、資金が流用され蓄えが使い切られることになります。 

操作上の安全性、多重のアクセス制限、（伝統的な銀行が行っているような）監査といったものに多額の投資を行う用意がない限り、Bitcoinの分散化された安全性の考え方に反した状態で資金を持つことには、よほど慎重でなければいけません。たとえ、頑健な安全性モデルを実装するだけの資金と規律（？）があったとしても、なりすましや買収や横領に苦しめられてきた、伝統的な金融ネットワークという脆弱なモデルを、複製しているに過ぎないのです。Bitcoinのユニークな分散化された安全性モデルの強みを活かすためには、親しみは感じるけれども結局はBitcoinの安全性を脅かすことになる、集中化されたアーキテクチャへの誘惑を断たねばなりません。

==== 信頼の根源

((("root of trust")))((("security","root of trust")))伝統的な安全性のアーキテクチャは「信頼の根源」という概念に基づいています。それは、システムやアプリケーション全体の安全性の礎となる、信頼の中核です。安全性のアーキテクチャは、信頼の根源を中心にして同心円状に（タマネギのように）構成され、中心から外向きに信頼が広がっていく形をとります。各層は、より信頼度の高い内側の層に依っており、内側の層は、アクセス制限、デジタル署名、暗号化、安全性に関するその他の素朴な技術（？？）を用いています。ソフトウェアシステムが複雑化するにつれ、システムの安全性が脅かされるようなバグを含むことが多くなってきています。結果、ソフトウェアがより複雑なものになると、それを安全な状態に保つことはより難しくなります。信頼の根源の概念をもとにすると、信頼のほとんどは、システムのうちで最も複雑でない部分、従って最も脆弱でない部分に置かれ、その周囲に複雑なソフトウェアが層を成すことになります。この安全性のアーキテクチャは、異なる規模で繰り返されます。すなわち、最初は単一のシステムのハードウェアに信頼の根源が据えられ、その信頼の根源が、OSを通じてより高いレベルのシステムの働きにまで拡張され、最終的には、外に向かって信頼度が低下する同心円上に配置された、多くのサーバーまで拡がりるのです。 

Bitcoinの安全性のアーキテクチャは異なります。Bitcoinでは、合意形成システムは、信頼できる公開された元帳を作り出し、その元帳は完全に分散化されたものです。正しく認証されたブロックチェーンは原初ブロックを信頼の根源として用い、最新のブロックまで続く信頼の連鎖を作り上げます。Bitcoinシステムはブロックチェーンを信頼の根源として用いることができますし、またそのようにしなければいけません。サービスの提供先が多くの異なるシステムであるような、複雑なBitcoinアプリケーションを設計するときには、どこに信頼が置かれようとしているかを明確にするため（？？）、安全性のアーキテクチャを注意深く精査する必要があります。結局、明確に信頼されるべき唯一のものは、完全に認証されたブロックチェーンなのです。明示的にであってもそうでなくても、あるアプリケーションがブロックチェーン以外のなにかに信頼の基礎を置いている場合、脆弱性を招き入れることになり、心配の種になるに違いありません。開発中のアプリケーションの安全性のアーキテクチャを評価する良い方法は、個々の構成要素を考え、その構成要素が悪意のある主体の管理下に置かれ、完全に毀損されるという仮説のシナリオを吟味することです。構成要素を一つ一つとりあげ、その構成要素が毀損されたとしたときの、全体の安全性に与える影響度を算定するのです。もし、構成要素が毀損されたときにアプリケーションが安全でなければ、それらに誤って信頼を置いていたことが分かります。脆弱性のないBitcoinアプリケーションとはつまり、Bitcoinの合意形成メカニズムが毀損されることに対してのみ、脆弱なアプリケーションです。それは、信頼の根源が、Bitcoinの安全性のアーキテクチャの中でも、最も強い部分に基づいていることを意味します。 

ハックされたビットコイン交換所の数多くの事例を見れば、この点ははっきり分かります。なぜなら、彼らの安全性のアーキテクチャと設計は、誰からも全くと言っていいほど監督されていないからです。交換所において集中化された交換が実施されてきたことは（？？）、ホットウォレット、集中化された元帳データベース、脆弱な暗号キーといった、ブロックチェーンから離れた多くの構成要素を、信頼できるものとして明確に位置付けた上でのことでした。 


=== 安全性に関するベストプラクティス

((("security","user", id="ix_ch10-asciidoc1", range="startofrange")))((("user security", id="ix_ch10-asciidoc2", range="startofrange")))人類は、物理的な脅威から安全を守る手段を、何千年も用いてきました。これに対して、デジタルの世界の安全性に関する私たちの経験は、50年にも満たないものです。((("operating systems, bitcoin security and")))近頃の一般的な目的のOSは、非常に安全とは言えず、特にデジタルマネーの保存に適しているというわけでもありません。私達のコンピューターは、インターネットへの常時接続を通じ、外界からの脅威に常に晒されています。コンピューターは、多くのプログラマーによって作られたソフトウェアを何千と走らせ、そうしたソフトウェアは時として何の制約もなくユーザーのファイルにアクセスします。コンピューターにインストールされた何千ものソフトウェアのうち、詐欺ソフトがひとつでも紛れていたら、キーボードとファイルに障害が起こり、ウォレットアプリケーションに保管されたbitcoinが盗まれるかもしれません。コンピューターをウィルスやトロイの木馬がない状態に保つために、必要なメンテナンスの水準は、大多数のユーザーの技術を超えています。 

何十年にも亘る情報セキュリティ上の研究と進歩にも関わらず、デジタル資産は、明確な敵対者に対し、いまだに情けないほど脆弱です。金融機関や諜報機関や防衛産業における、最も高度に保護され機密性の高いシステムでさえ、頻繁に破られます。Bitcoinが作り出すデジタル資産は、固有の価値を持っており、盗難されてすぐに新たな所有者に送られ、戻ってこなくなり得るものです。このことは、ハッカーにとって大きなインセンティブとなります。これまでハッカーは、クレジットカードや銀行口座といった、個人情報や口座トークン（？）について、盗み出した後に価値あるものに変換しなければなりませんでした。盗んだ金融情報の換金やロンダリングは困難であるにもかかわらず、盗難は増える一方でした。Bitcoinはそれ自体が価値であるため、換金やロンダリングの必要がなく、この問題をより大きくしています。 

幸いなことに、Bitcoinはコンピューターのセキュリティを改善するインセンティブももたらします。以前は、コンピューターを危機に晒すリスクは、漠然としていて間接的でしたが、Bitcoinはこのリスクを明確なものにしています。bitcoinをコンピューターに保持することは、そのユーザーの関心を、コンピューターのセキュリティ改善の必要性に集中させることにつながります。Bitcoinや他のデジタル通貨の激増と拡がりの直接的な帰結として、私達は、ハッキング技術とセキュリティソリューションの両方が発展していく様子を見てきました。簡単に言えば、ハッカーは今やとても美味しいターゲットをみつけ、ユーザーは自分自身を守る明確なインセンティブを持っているわけです。 

過去３年にわたって私達は、ビットコインの拡まり（？？）の直接的な帰結として、ハードウェア暗号化、鍵保管、ハードウェアウォレット、マルチシグネチャー技術、デジタルエスクローといった、情報セキュリティ分野における素晴らしいイノベーションを目の当たりにしてきました。次項では、実践的なユーザーセキュリティのための、多様なベストプラクティスを詳しく取り上げることにしましょう。

==== 物理的なBitcoinの保管

((("backups","cold-storage wallets")))((("bitcoin","storage, physical")))((("cold-storage wallets")))((("paper wallets")))((("user security","physical bitcoin storage")))多くのユーザーは、情報として安全が保たれていることよりも、物理的に安全が保たれていることのほうに、はるかに安心を感じるので、bitcoinを物理的な形に変換するということは、bitcoinの安全な保持のために大変有効な方法です。Bitcoinの鍵は単なる長い数字の羅列です。このことは、鍵が、紙への印刷や、金属のコインへの刻印といった、物理的な形態で保存され得ることを意味しています。従って、鍵を安全に保つことは、bitcoinの鍵の紙のコピーを安全に保つことになります。紙に印刷されたBitcoinの鍵は「ペーパーウォレット」と呼ばれ、これを作るためのフリーツールが数多くあります。私は個人的に、自分のbitcoinのほとんど（99％以上）を、ペーパーウォレットに保存しています。そのウォレットはBIP0038で暗号化され、複数のコピーが鍵をかけた金庫に閉じ込んであります。Bitcoinをオフラインにしておくことはコールドストレージと呼ばれ、最も有効なセキュリティのテクニックのひとつです。コールドストレージシステムでは、鍵はオフラインシステム（インターネットに一度も接続したことがないシステム）で生成され、紙であれUSBメモリスティックのようなデジタルメディアであれ、オフラインで保存されます。 

==== ハードウェアウォレット

((("hardware wallets")))((("user security","hardware wallets")))((("wallets","hardware")))長い目で見れば、Bitcoinの安全性は、改竄に耐性のあるハードウェアウォレットの形態を、ますますとるようになるでしょう。スマートフォンやデスクトップコンピューターとは異なり、Bitcoinのハードウェアウォレットには、Bitcoinを安全に保有するというただひとつの目的しかありません。漏洩の原因となり得る一般的なソフトウェアがなく、インターフェースも限られるために、ハードウェアウォレットは、専門家でないユーザーに絶対と言っていいほど確実なセキュリティをもたらします。私は、ハードウェアウォレットは、Bitcoin保有の方法として広く用いられるようになると予想しています。このようなハードウェアウォレットの一例は、((("Trezor wallet")))Trezor (http://www.bitcointrezor.com/)をご覧ください[Trezor]。

==== リスクを比較衡量する

((("risk, security")))((("user security","risk, balancing")))ほとんどのユーザーは、bitcoinの盗難について適切に注意を払っていますが、盗難よりも大きなリスクが存在します。データファイルはいつでも失われます。もしそのファイルがbitcoinを含んでいたら、極めて悲惨なことになります。Bitcoinウォレットを安全に保護しようと努力するあまり、やり過ぎてbitcoinを失うことにならないよう、ユーザーは注意深くならなければいけません。2011月7月、有名なBitcoinの教育啓発プロジェクトが、ほぼ7,000 bitcoinを失いました。盗難防止の努力の一環として、彼らは複雑に暗号化されたバックアップを実施していました。結局、彼らは暗号化鍵を誤って失くし、バックアップは無価値となり、財産を失いました。砂漠に埋めてお金を隠すように、bitcoinを安全にし過ぎると、二度と見つけられなくなるかもしれません。

==== リスク分散

((("user security","risk, diversifying")))あなたは、全財産を現金で財布の中に入れて持ち運びますか？ほとんどの人はこのようなことは向こう見ずと考えるのにもかかわらず、Bitcoinユーザーは、全てのbitcoinをひとつのウォレットに入れてしまうことがよくあります。そうではなくて、ユーザーは、複数の多様なBitcoinウォレットに、リスクを分散しなければなりません。慎重なユーザーは、自分のbitcoinのうちほんの少しだけ、おそらく5％に満たない程度を、オンラインまたはモバイルウォレットに「小銭」として持つようにしています。残りのbitcoinは、デスクトップウォレットやオフライン（コールドストレージ）のような、複数の異なる仕組みで保管されなければなりません。

==== マルチシグネチャーと管理

((("corporations, multi-sig governance and")))((("governance")))((("multi-signature addresses","security and")))((("security","governance")))((("security","multi-signature addresses and")))企業や個人が多額のbitcoinを保管するときはいつでも、マルチシグネチャーbitcoinアドレスを用いることを考慮すべきです。マルチシグネチャーアドレスは、支払いに複数のサインを要求することで、資金を安全に守るものです。サインのための鍵は、複数の異なる場所に保管され、別々の人によって管理されなければなりません。たとえば、企業では、サインのための鍵が別々につくられ、複数の幹部によって保持され、誰であれ一人では資金に手を出せないようになっていないといけません。マルチシグネチャーアドレスを用いることで、冗長性を得る、すなわち、一人の人が複数の鍵を別々の場所に保持することも、可能となります。

==== サバイバビリティ

((("bitcoin","death of owner and")))((("death of owners")))((("security","death of owner and")))((("security","survivability")))((("survivability")))安全性に関して、見過ごされがちですが考慮すべき重要な点として、鍵の持ち主が動けなくなったり死亡したりした場合に、どうやってbitcoinを手にするかということがあります。Bitcoinユーザーは、複雑なパスワードを用い、鍵を安全で秘匿された状態に保ち、誰とも共有してはいけない、と言われてきました。不幸なことに、こうしたプラクティスによって、ユーザー自身が鍵を使えないときに、ユーザーの家族が資金を再び手にすることはほとんど不可能です。実際、Bitcoinユーザーの家族は、bitcoinの資産の存在に全く気付かないことがほとんどでしょう。

多額のbitcoinを持っているのであれば、アクセスの詳細を信頼のおける親戚や弁護士と共有することを考えるべきです。より複雑なサバイバビリティの仕組みは、マルチシグネチャーアクセスと、「デジタル資産の遺言執行者」（？？）に特化した弁護士を通じて計画する財産（？？）から構成されます。

=== 結び

Bitcoinは全く新しい、先例のない、そして複雑なテクノロジーです。いずれは、専門家でないユーザーにも使いやすい安全性のためのツールやプラクティスが、開発されることでしょう。差し当たり、Bitcoinユーザーは本書で扱った多くのTIPSを用いることで、安全でトラブルのないBitcoinエクスペリエンスを楽しむことができます。(((range="endofrange", startref="ix_ch10-asciidoc2")))(((range="endofrange", startref="ix_ch10-asciidoc1")))(((range="endofrange", startref="ix_ch10-asciidoc0")))
