[チャプター9]
== 代替のチェイン、通貨、パスワード:[<phrase role="keep-together">and Applications</phrase>]

ビットコインは20年の分散形のシステムと通貨のリサーチの結果だった、そしてその分野に新しい技術革新をもたらした。分散形のコンセンサスのメカニズムは、Proof of Workに基づいている。この発明はビットコインのコアとなる発明であり、通貨、金融サービス、経済、分散形のシステム、投票システム、コーポレート・ガバナンス、そして契約の分野において、革命の波をもたらした。 

このチャプターは、Bitcoinとブロックチェーンの発明についての様々な分岐点を調査する。2009年のテクノロジーの革新が始まった。大半の代替コイン、言い換えると、オルトコインを我々は見ていく。（同じデザインパターンで実装されたが、異なるブロックチェーンとネットワークで運用されるコイン） 

このチャプターで紹介されるオルトコインの中に、50やそれ以上の名前を挙げられていないものがあることを、それらの製作者や、ファンからもたらされた怒りの声を沈めるために述べておく。このチャプターの目的は、オルトコインの質を評価することではなく、また最も重要なものを主観的な査定によって述べることではなく、我々はいくつかの例をビットコインエコシステムの中での幅と種類を紹介するために注釈する。第一種のそれぞれのイノベーションには重大な違いがある。いくつかの大変興味深いオルトコインの例の中には、実際には、お金として考えると完全な欠点を持っているものも有る。そのことは、研究するに当たってより一層興味深いかもしれない。そして、このチャプターは投資のガイドとしての仕様を意図していないことを注釈しておく。 

新しいコインは毎日紹介され、いくつかの重要なコイン、それも歴史を変えるかもしれないコインが見逃されないようにすることは不可能だろう。イノベーションの速度はとても刺激的な程に早く、このチャプターは直ぐに不完全で時代遅れなものになるだろう。

=== オルトコインとチェーンの分類

((("chains, alternative")))((("currencies, alternative")))ビットコインはオープンソースのプロジェクトで、そのコードは他の多くのソフトウェアプロジェクトのベースとして使われている。最も一般的なビットコインのソースコードから生まれたソフトウェアは、分散形の代替コイン、_オルトコイン_である。オルトコインはデジタル貨幣を実装するための同じブロック建設のための基礎を使って作られている。 

ビットコインのブロックチェーン上に実装されたいくつものプロトコルのレイヤーがある。これらは(((("blockchain apps")))((("meta chains")))((("meta coin platforms"))) _meta coins_, _meta chains_, or _blockchain apps_では、ブロックチェーンをアプリケーションのプラットフォームとして、もしくはビットコインのプロトコルにプロトコルのレイヤーを加えることによって拡張して使用している。例としては、ColoredCoins, Mastercoin、NXT、そしてCounterpartyがある。 

次のセクションでは、我々はいくつかの特筆すべきオルトコインを調査する、例えば、Litecoinや、Dogecoin、Freicoin、Primecoin、Peercoin、Darkcoin，そしてZerocoinである。これらのオルトコインは、最も価値がある、また"最良"のオルトコインであるがためというわけではなく、また特定の分野のオルトコインのイノベーションの例として彼らが良い例であるために、歴史的な理由故に特筆する価値がある。 

オルトコインに加えて、幾つかのブロックチェーンの実装の代替案では、それらは決してコインではない。私が((("alt chains"))) _alt chains_. と呼ぶものである。、_オルトチェーン_、ではこれらのオルトチェーンは、コンセンサスの仕組みを実装しており、そして契約のためのプラットフォーム、名前登録、もしくは他のアプリケーションとして、分散形の台帳である。オルトチェーンは同じブロックの建設法を用いており、ときどき通貨もしくはトークンをその支払いに使用している。だがその第一義の目的は、通貨ではない。我々はネームコインと、Ethereumをオルトチェーンの例として見ていく。 

最後にこれらのいくつかのビットコインのデジタル通貨もしくはデジタル決済システムのネットワークを提供している競争者があるが、Proof of workに基づく分散形の台帳やコンセンサスのメカニズムを使うことなしに動いているRippleや他の通貨がある。これらのブロックチェーンのテクノロジーでないものは、この文書の外部として、このチャプターでは扱わない。

===メタコインのプラットフォーム 

((("meta coin platforms", id="ix_ch09-asciidoc0", range="startofrange")))メタコインと、メタチェーンはビットコイン上に建てられたソフトウェアのレイヤーであり、通貨内通貨、もしくはビットコインシステムの内側のプラットフォームや、プロトコルのオーバーレイとして実装されている。これらの機能のレイヤーは、ビットコインのコアの機能を拡張し、追加のデータをビットコインのトランザクションとアドレスの内側でエンコーディングすることによって、機能と可能性を加えている。様々なメタデータをビットコインのブロックチェーンに加えるための最初のメタコインの実装は、例えばビットコインのアドレスを使ってデータをエンコードすることや、使われていないトランザクションのフィールドを使うようなものだ（例、トランザクションのシークエンスのフィールド）。追加されたプロトコルのレイヤーについてメタデータをエンコードするための使われていないトランザクションのフィールドを用いることがある+OP_RETURN+のトランザクションを導入してオプコードのスクリプトを走らせるられるようになったので、メタコインはブロックチェーン上にメタデータを記録することがより直接的に出来るようになってきた、そして大半のコインはその方法を代わりに用いている。 

====Colored Coins

((("colored coins")))((("meta coin platforms","colored coins")))_Colored coins_  は、少量のビットコイン上に情報をオーバーレイするメタプロトコルである。ある"Colored"コインは、他のアセットを述べるために再目的化されたある量のビットコインであるということだ。 ((("stock certificates","colored coins as")))考えて見て欲しい、例えば$1札を取り出して、そこにスタンプを押し、"これはAcme Incの1 株のシェアの証明だ"と述べていることを。"今$1札が2つの目的に値する": それは通貨としての貴重そして、共有の証明だ。共有として最も価値があるのはシェアとしての価値であるため、決してそれをキャンディを買うために$1札を使おうとはしないだろう。それゆえに、もはや通貨としては有用ではないようにすることが効果的に出来る。Colored coinsは同じやり方を行って成り立っている。特定のとても小さな量のビットコインを他のアセットを証明している交換のための証明に変換している。"Color"の言葉が示しているのは、色のように追加された属性を通して生まれた特別な意味のアイディアについて述べている。カラーはメタファーであり、実際に色とは関連がない。Colored coinsには色は無い。 

((("wallets","for colored coins")))Colored coinsは、colored bitcoinsに与えられたメタデータを記録し、解釈出来る特別なウォレットによって管理されている。そのようなウォレットを使うことに依って、ユーザーはビットコインの総量を色のついていないビットコインから色の付いているビットコインへ特別な意味を持つラベルを加えて変換するだろう。例えば、株式の証明、クーポン、不動産、日用品、そして収集可能なトークンを表象するラベルにおいては、カラードコインのユーザーが特定のコインの"Color"の意味に何を加えて解釈するかは完全にユーザーに委ねられている。そのような発行の形式では、象徴や叙述、そして他の関連する情報へとより小さなユニットに切り分けられることが出来る。一旦色が付くと、これらのコインは購入し販売し、分割し、集められることが出来る。そして分散された支払いを受け取る事が出来る。色のついたコインから特定の紐付けられた価値を取り除き、ビットコインとしての元々の価値を取り戻すことも出来る 

Colored coinの使用を実際に見せるために、我々は20個の"MasterBTC"の象徴の名前を持つカラードコインのセットを作っておいた。それはこの本の <<example_9-1>>無料のコピーへのクーポンを表しており、それぞれのMaterBTCのユニットは、これらのColoredcoinによって表彰されており、colored-coin使えるウォレットを持っていてあらゆるビットコインのユーザーに対して販売したり、与えたりすることが出来る。MasterBTCを得たユーザーは、無料の本のコピーの発行者と共に人に送ったり、取り戻したりすることが出来る。このcolored coinの例は、 https://cpr.sm/FoykwrH6UY[here]から見ることが出来る。

[[example_9-1]]
それらのcolored coinsのメタデータのプロフィールは、本の無料のコピーに対してのクーポンとして記録された。
====
[source,json]
----
{
  "source_addresses": [
    "3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD"
  ],
  "contract_url": "https://www.coinprism.info/asset/3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD",
  "name_short": "MasterBTC",
  "name": "Free copy of \"Mastering Bitcoin\"",
  "issuer": "Andreas M. Antonopoulos",
  "description": "This token is redeemable for a free copy of the book \"Mastering Bitcoin\"",
  "description_mime": "text/x-markdown; charset=UTF-8",
  "type": "Other",
  "divisibility": 0,
  "link_to_website": false,
  "icon_url": null,
  "image_url": null,
  "version": "1.0"
}
----
====

==== Mastercoin

((("meta-coin platforms","mastercoin protocol")))Mastercoinは、ビットコイン上のトップのレイヤーに位置するプロトコルであり、様々な種類のビットコインシステムを拡張したアプリケーションのためのプラットフォームとなっている。MastercoinはMSTという通貨を、Mastercoinのトランザクションを行うためのトークンとして使用しており、だがそれは第一義的な通貨というよりもむしろ、他のもの例えばユーザーの通過や、スマートプロパティのトークンや、分散形のアセットの取引所を建てるためのプラットフォームであり、Bitcoinの財務的なトランザクションを送るレイヤー上にあるアプリケーションのレイヤーとして、Mastercoinについて考えると、それはHTTPがTCP層の上に走っているように考えられる。 

Mastercoinは特別なビットコインのアドレスへ、もしくはそのアドレスから送るトランザクションを主に通して作用する。その特別なアドレスは((("exodus addresses"))) "exodus" アドレスと呼ばれている。(+1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P+),HTTPが特定のTCPポートを使って働いているように、残りのTCPのトラフィックから動くトラフィックは差別化されている。マスターコインのプロトコルは、だんだんと特別なExodusアドレスと、ビットコインのトランザクションのメタデータをエンコードするためのOP_RETURNを使うプロトコルから移行してきている。

====Counterparty

((("meta coin platforms","counterparty protocol")))Counterpartyは、ビットコイン上に他のプロトコルレイヤーとして実装された。Counterpartyはユーザーによる通貨や交換可能なトークン、金融的なツール、分散形のアセット取引所と、他の機能を可能としている。Counterpartyは、ビットコインのスクリプト言語の中で、ビットコインのトランザクションに追加の意味を持たせるメタデータを記録する+OP_RETURN+のオペレーターを主に使って、実装されている。Counterpartyは、Counterpartyのトランザクションを実行するためにXCPをトークンとして用いている。(((range="endofrange", startref="ix_ch09-asciidoc0"))) 

=== Alt Coins 

((("alt coins", id="ix_ch09-asciidoc1", range="startofrange")))((("currencies, alternative", id="ix_ch09-asciidoc2", range="startofrange")))大半のオルトコインは、ビットコインのソースコードから由来しており、中には"フォーク"として知られているものも有る。いくつかの実装は、ブロックチェーンのモデルに基いて”スクラッチで”制作されたが、どのビットコインのソースコードも用いていないものもある。オルトコインとチェーン（次のセクションで述べる）は、どちらも別々のブロックチェーンテクノロジーの実装であり、どちらの形式も自らのブロックチェーンを用いている。その言葉の定義の違いは、オルトコインが通貨として主に使われている一方で、オルトチェーンは通貨を主目的としない他の目的のために使われていることに有る。 

厳密にいうと、最初の大きな"オルト"のビットコインのソースコードのフォークは、オルトコインではなく、オルトチェーンである、_Namecoin_、であり次のセクションで言及する。 

発表された日付に基づくと、ビットコインのフォークとしての最初のオルトコインは、 2011年8月に登場した_IXCoin_.だ。IXCoinはいくつかのビットコインのパラメーターを修正したもので、取り分けブロックごとに96コインずつリワードを加えていくと云う方法で、通貨の生成を加速させようとしていた。

2011年の9月には、_Tenebrix_ が始まった。 Tenebrix は最初のProof of workのアルゴリズムの代替手段を始めて実装した暗号通貨であり、その名前は((("proof-of-work algorithm","alternative")))((("scrypt algorithm"))) _scrypt_という。それはパスワードをストレッチするためにもともと作られたアルゴリズムである( ブルートフォースアタック対策）。Telebrixのゴールは、メモリーに集中させるアルゴリズムを用いることによって、GPUや、ASICSによるマイニングに対抗できるコインを作ることだった。Tenebrixは、貨幣としては成功しなかったが、Litecoinの基礎となり、何百ものクローンを生み出す成功へと繋がった。 

_Litecoin_は、スクリプトをProof of Workのアルゴリズムとして使うことに加えて、Blockの生成速度を早くする実装を行っており、Bitcoinの10分毎の代わりに2.5分毎にブロックが生成される。結果として、"ビットコインが金ならば、Litecoinは銀"として考えられており、それは軽量な代替貨幣を意図されている。多くのLitecoinの魅力的な部分は、小売業のトランザクションにBitcoinよりも適していると考えられている。 

オルトコインの2011年、2012年の間に激増した、Bitcoinに基づくコイン、ないし、Litecoinに基づくコインである。20ものオルトコインは、市場での位置をとりに競争した。2013年の終わりには、200に迄達し、2013年は"オルトコインの年"に素早く変化した。オルトコインの成長は2014年迄続き、今執筆している時には、500以上ものオルトコインが存在することとなっている。半数以上のオルトコインは、Litecoinのクローンである。 

オルトコインを作り出すことは簡単であり、それゆえに500以上のオルトコインが存在している。大半のオルトコインは、ビットコインとまさに少しだけ異なっており、学ぶ価値がないものが多い。オルトコインは、制作者が儲けようとしているだけのものが実際には多い。これらのコピーと、パンプアンドダンプを仕掛けようとしているコインの中には、特筆すべき例外があり、非常に重要なイノベーションとなっているものがある。それらのオルトコインは、急進的で、異なるアプローチを取っており、重要なイノベーションをビットコインのデザインパターンに対して与えている。ビットコインから異なっているこれらのオルトコインについて、3つの重要な分野がある。

* 異なる貨幣としてのポリシー
* 異なるProof of workもしくはコンセンサスアルゴリズム
* 特定のフィーチャー、例えば強力な匿名性

さらなる情報はこちらに記載してある。http://mapofcoins.com[graphical timeline of alt coins and alt chains].((("alt chains","timeline of")))((("alt coins","timeline of")))

==== Alt coinの価値評価

((("alt coins","evaluating")))((("currencies, alternative","evaluating")))あまりにも沢山のオルトコインが生まれている中で、どのようにしてどれが注目すべきだと決めるべきだろうか？幾つかのオルトコインは広く普及させることを達成しようとしており、通貨として使おうとしている。他には、異なる機能や、金融のモデルを試すための試金石として作られているものもある。多くのものは、ただ制作者がすぐに儲けようととしているだけのものだ。オルトコインを価値評価するためには、その定義された特徴と、マーケット指標を見ている。

ここに幾つかの疑問が生まれる。どれだけオルトコインはビットコインから異なっているのか？

* オルトコインは、大きなイノベーションをもたらしているのか
ユーザーがビットコインから引きつけられるだけの競争力のある違いを持っているのか？
* そのオルトコインは、ニッチなマーケットやアプリケーションに対して魅力を訴えているのか？
* そのオルトコインは、コンセンサスに対しての攻撃を行えないだけのセキュリティを持てるほどマイナーにとって魅力があるのか？

ここにいくつかのキーとなる考えるべき金融面とマーケットでの指標を表す。

* オルトコインのマーケット内でのキャピタリゼイションはいくらか？
* どれだけのユーザーとウォレットを持っていると見積もられているか？
* どれだけのビジネスがオルトコインを受け入れているか？
* どれだけの毎日のトランザクション（ボリューム)がオルトコインで行われているか？
* どれだけの価値が毎日トランザクションされているか？

このチャプターでは、特に技術的な特徴と、先の質問によって代表されるイノベーションの潜在価値に対して集中して述べる。

==== 金融的な代替案として: Litecoin、Dogecoin、Freicoin

((("alt coins","monetary parameter alternatives")))((("currencies, alternative","monetary parameter alternatives")))((("monetary parameter alternatives")))ビットコインはいくつかの金融指標は特徴的な機能を持っており、固定された発行されているそして21百万の大きな通貨のユニットを (21 ×10の48乗の小さなユニット)。そして地理的に発行レートが減少するにつれて、そして10分のブロック”ハートビート”、これがトランザクションの承認時間の速さ多くのオルトコインは、異なる金融的なポリシーを達成するために主となるパラメーターを引張ってきた何百ものオルトコインの中、最も特筆すべき例の中での幾つかのコインでは下記のパラメーターを含んでいる。

===== Litecoin

最初のオルトコインの1つは、2011年にリリースされたLitecoinであり、二番目に最も成功しているBitcoinの後のデジタル通貨だ。主要なイノベーションは、_scrypt_をproof of workのアルゴリズムとして使用し(Tenebrixから受け継いでいる）、それは軽量で高速な通貨のパラメーターである。

* ブロック生成速度 2.5分
* 通貨の合計: 84 milliionのコインを2140年迄に発行
* コンセンサスアルゴリズム: Scrypt proof of work
* マーケット・キャピタラゼイション: 2014年中旬に$ 160 million 

===== Dogecoin

Dogecoinは2013年の１２月にリリースされたLitecoinのフォークに基づくものだ。Dogecoinは、消費することと、チップを支払うことを奨励しているがために、速い発行ととても高い通貨の時価総額を金融政策を持っているがために、特筆すべき価値がある。2014年に急速に価値が下がる前は、Dogecoinは、初めはジョークとして始まったが次第に、活発で大きなコミュニティと共に大変有名になったものだった。 

* Blockの生成速度: 60秒
* 総発行量 : 2015年迄に 100,000,000,000 (100 billioin) Doge 
* コンセンサスアルゴリズム: Scrypt proof of work
* 市場総額: 2014年中旬に$12 million 

===== Freicoin

Freicoinは2012年の7月に発表された。それは((("demurrage currency"))) _demurrage currency_であり、保存している価値に対してマイナスの利子率を持っている。Freicoinを持っていると、消費を奨励し、お金を所持し続けることを抑制するために4.5%のAPR費用が掛かるようになっている。FreicoinはBitcoinのデフレ政策とは正反対の金融政策を導入しているという点で特筆すべき価値がある。Freicoiは通貨としては成功しなかったが、金融政策の一種として興味深い例となっている。

* Block生成時間: 10分
* 通貨発行量: 2140年迄に 100million コイン
* コンセンサスアルゴリズム: SHA256のProof of work
* 市場規模: 2014年中旬で、$130,000 

==== コンセンサスのイノベーション: Peercoin, Myriad, Blackcoin, Vericoin, NXT

((("alt coins","consensus innovation")))((("consensus","innovation")))SHA256のアルゴリズムを用いたProof of workにビットコインのコンセンサスのメカニズムは基づいている。最初のオルトコインは、Proof of workに代わる手段としてスクリプトを導入した、そしてマイニングのプロセスをよりCPUに優しく、ASICSによる中央集権化にならないようにした。それ以降コンセンサスのメカニズムにおけるイノベーションは激しいペースで続いた。いくつかのオルトコインは、スクリプトのように様々なアルゴリズムを導入した。("Blake algorithm")))((("Groestl algorithm")))((("scrypt-N algorithm")))((("SHA3 algorithm")))((("Skein algorithm"))) Scrypt-N, Skein, Groestl, SHA3, X11, Blake、等々だ。いくつかのオルトコインは、様々なProof of workのアルゴリズムと結びついた。そして2013年には、我々はProof of workの代替手段の発明を見た、それは((("proof of stake"))) _proof of stake_と呼ばれるもので、いくつもの最近なオルトコインのベースを構成している。 

Proof of stakeは既存の貨幣の所有者が利子を持っている担保として、貨幣の所有を主張することが出来るシステムである。それはいくらかデポジットの証明に似ていて、参加者は、投資のリターンを新しい貨幣の形式（利子の支払のように発行される）、そしてトランザクションのフィーから稼ぎながら、通貨の一部を保有することが出来る。 

===== Peercoin

Peercoinは、2012年8月に発表されProof of workと Proof of stakeのアルゴリズムを取り入れた最初の貨幣として発行されたオルトコインである。 

* Block生成時間: 10分
 * 総発行量: 無制限
* コンセンサスアルゴリズム: (ハイブリッド)Proof of workで始まるProof of stake
* 市場規模: 2014年中旬で$14 million

===== Myriad

Myriadは2014年の2月に発表され、5つの異なるProof of workのアルゴリズムを用いている(SHA256d, Scrypt, Qubit, Skein, そしてMyriad-Groestl)を同時に使っており、マイナーの参加に応じてそれぞれのアルゴリズムごとに異なる難易度がある。その意図はMyriad をASICに対して耐久性のあるものとし、多数のマイニングのアルゴリズムは、同時多発的に攻撃しなければならないようにすることによって、出来るだけコンセンサスに対しての攻撃に強くしようとしているためである。

* ブロック生成時間: 30秒が平均(マイニングのアルゴリズムごとに2.5 分がターゲット）
* 総発行量 2024年前に20億
* コンセンサスアルゴリズム: Proof of workの様々なアルゴリズム
* 市場規模: 2014年中旬に$120,000 

==== Blackcoin

Blackcoinは2014年の冬に発表され、Proof of stakeのコンセンサスアルゴリズムを用いている。特筆すべき点は、"multipools"を導入したことで、どのコインをマイニングするか異なるオルトコインの間を自動的に利益によって変更するマイニングプールの形式である。 

ブロック生成時間: 1分
 * 総発行量: 無制限
* コンセンサスアルゴリズム: Proof of stake
* 市場規模: 2014年中旬で$3.7 million 

===== VeriCoin

VeriCoinは2014年の5月に始まり、Proof of stakeのコンセンサスアルゴリズムを用いてて、異なる利子のレートを用いている。動的にマーケットの供給力に基いて変更される。それはウォレットからビットコインを支払う際に、自動取引所の機能を導入した始めてのオルトコインである。

ブロック生成時間: 1分
 * 総発行量: 無制限
* コンセンサスアルゴリズム: Proof of stake
* 市場規模: 2014年中旬で$1.1 million

====== NXT

NXT (発音は"Next")は、Proof of workによるマイニングを用いていないと云う点で純粋なProof of stakeのオルトコインだ。NXTはスクラッチから実装された暗号通貨で、ビットコインのフォークでも、他のオルトコインのフォークでもない。NXTは沢山の先進的な機能を実装しており、例えば名前登録機能(((("Namecoin"))) と似ている、Namecoin), 分散形のアセット取引所(Colored Coinsと似ている）、分散形の統合された安全なメッセージング機能((("Bitmessage"))と似ている)そしてStake delegationシステムだ。(Proof of stakeを他人に委譲すること）NXTに惹き付かれている人は、NXTを"次世代"、または2.0世代の暗号通貨と呼んでいる。 

ブロック生成時間: 1分
 * 総発行量: 無制限
* コンセンサスアルゴリズム: Proof of stake
* 市場規模: 2014年中旬で3千万ドル


==== 2つの目的を持ったマイニングのイノベーション: Primecoin, Curecoin, Gridcoin

((("dual-purpose mining")))((("mining","dual-purpose")))ビットコインのProof of workのアルゴリズムは、只一つの目的がある。それはビットコインのネットワークをセキュアに保つことである。伝統的な決済のシステムのセキュリティに比べて、マイニングのコストはあまり高くない。しかしながら、多くの人に無駄が多いとして批判されてしまう。次の世代のオルトコインは、この問題に対処しようとしている。2つの目的を持つProof of workのアルゴリズムは、ネットワークをセキュアに保つ。外部の使用の使い方を付け加えることで、通貨のセキュリティは、それは外部の影響を需要と供給の曲線に与えることとなる。 

===== Primecoin

Primecoinは2013年の7月に発表されたProof of workのアルゴリズムを持つコインであり、素数を探す((("bi-twin prime chains")))((("Cunningham prime chains"))) コンピューティングを行う。素数は、多様な科学的な 

ブロック生成時間: 1分
 * 総発行量: 無制限
* コンセンサスのアルゴリズム: 素数の発見のチェーンによるProof of work
* 市場規模: 2014年中旬に130万ドル

===== Curecoin

((("protein folding algorithms")))Curecoinは2013年5月に発表されたコインである。Folding@Home のプロジェクトを通した、タンパク質のフォールディングの研究を、SHA256のProof of workのアルゴリズムと結び付けている。タンパク質のフォールディングは、病気を直す新薬の発見のために使われているタンパク質の科学的な相互作用についての多大なコンピューターによるシミュレーションである。 

* Block生成時間: 10分
 * 総発行量: 無制限
* コンセンサスアルゴリズム; タンパク質のフォールディングの研究と共に働くProof of work
* 市場規模: 2014年中旬に$58,000 

==== Gridoin

Gridcoinは2013年に発表された。ScryptベースのProof of workを行っており、((("BOINC open grid computing"))) BOINCへの参加の支社としてのProof of workである。BOINCはBerkeley Open Infrastrucure for Network Computing であり、科学的なグリッドコンピューティングに対してのオープンプロトコルである。それにより、参加者は、空いているコンピューターのスペースをを共有して、科学的な研究のコンピューティングが出来るようになる。GridcoinはBOINCを、例えばタンパク質のフォールディング問題のような特定の問題を解決するためにではなく、一般的な目的のコンピューティングプラットフォームとして用いている。 

* ブロックの生成: 150秒ごと
 * 総発行量: 無制限
* コンセンサスアルゴリズム:  BOINCのグリッドコンピューティングによるProof of work
* 市場規模: 2014年中旬で、122,000ドル

==== 匿名性に集中したオルトコイン: CryptoNote Bytecoin Monero, Zerocash/Zerocoin, Darkcoin

((("alt coins","anonymity focused", id="ix_ch09-asciidoc3", range="startofrange")))((("currencies, alternative","anonymity focused", id="ix_ch09-asciidoc4", range="startofrange")))ビットコインは良く、"匿名"のコインとして間違われる。実際には、ビットコインのアドレスとIDを紐付けることは簡単だ、そしてビッグデータ解析を使えば、アドレスと個人の間にあるどのようにしてビットコインを使っているかの週間についての包括的な図を作成することが出来る。幾つかのオルトコインでは、強い匿名性を目的として行っているものがある。その最初の取り組みは、_Zerocoin_である。Zerocoinは、セキュリティとプライバシーについての2013年のIEEEのシンポジウムの文書で発表された、ビットコイン上で匿名性を保つためのメタコインである。Zerocoinは、書いている間の開発で完全に分けられたZerocashという名のオルトコインとして導入されるだろう。2013年10月に発表された匿名性のための代わりの手段として_CryptoNote_と共に始まった。CryptoNoteは、次に議論する数多くのオルトコインのフォークに依って実装された根本的な技術である。ZerocashとCryptoNoteに加えて、いくつもの匿名の独立したコインが存在している、例えば、Darkcoinは、ステルスアドレスと、匿名性のためのトランザクションのミクシングを行っている。

===== Zerocoin/Zerocash

Zerocoinは、Johns Hopkinsのリサーチャーによって2013年に導入されたデジタル通貨の匿名性に対しての理論的な試みである。ZerocashはZerocoinのオルトコインとしての実装であり、それは開発段階で、未だリリースされていない。 

===== CryptoNote

CryptoNote、匿名の電子的な現金として使えるようにするための基礎を提供するオルトコインの実装である。2013年10月に発表された。異なる様々な実装にフォークされる用に設計されており、一定周期で貨幣として利用できなくなるようにリセットするメカニズムを備えている。多数のオルトコインは、CryptoNoteから生まれてきた。 Bytecoin (BCN), Aeon (AEON), Boolberry (BBR), duckNote (DUCK), Fantomcoin (FCN), Monero (XMR), MonetaVerde (MCN), そして Quazarcoin (QCN)である。CryptoNoteはビットコインのフォークではなく、暗号通貨の実装を完全にまとめたものとして存在していることに特筆すべき価値がある。 

===== Bytecoin

((("Application Specific Integrated Circuit (ASIC)")))((("Graphical Processing Units (GPUs)"))BytecoinはCryptoNoteから生まれた最初の実装であり、CryptoNoteの技術に基づく匿名の貨幣としての性質を提供している。Bytecoinは2012年の7月に始まった。以前のオルトコインでBTEのシンボルとしてBytecoinが存在していた。CryptoNoteに由来するBytecoinは、貨幣としてのシンボルはBCNである。Crytponight Proof of workのアルゴリズムでは、少なくとも2MBのRAMをインスタンスごとに必要としており、GPUや、ASICのマイニングには適して」いないようになっている。Bytecoinは、円状の署名を受け継いでおり、リンク不可能なトランザクションと、CryptoNoteから受け継いだBlockchain解析に対しての匿名性を持っている。

* ブロック生成: 2分
* 総発行量: 1840 億 BCN
* コンセンサスアルゴリズム: Cryptonight Proof of work
* 市場規模  2014年中旬に300万ドル

===== Monero

Monero はCryptoNoteの一種の実装である。それはBytecoinよりも幾分フラットな発行曲線を持っていて、80%の貨幣は最初の4年間の間に発行される。そして、CryptoNoteから受け継いだ同様の匿名性の機能を持っている。

ブロック生成時間: 1分
* 総発行量: 1840万 XMR
* コンセンサスアルゴリズム: Cryptonight Proof of work
* 市場規模: 2014年中旬の500万ドル

====== Darkcoin

Darkcoinは2014年の1月に始まった。Darkcoinは匿名の貨幣として実装されており、Darksendと呼ばれる全てのトランザクションに対してのre-mixingプロトコルを用いている。Darkcoinは、Proof of workのアルゴリズムに、11ラウンドの異なるハッシュのファンクションを用いていることで、特筆すべき価値がある。((("proof-of-work algorithm","for Darkcoin"))) (blake, bmw, groestl, jh, keccak, skein, luffa, cubehash, shavite, simd, echo) 

* ブロック生成: 2.5分毎
*  総発行量: 最大2200万DRK
* コンセンサスアルゴリズム: 複数のアルゴリズムと複数回のProof of work
* 市場規模: 2014年中旬に1900万ドル(((range="endofrange", startref="ix_ch09-asciidoc4")))(((range="endofrange", startref="ix_ch09-asciidoc3")))(((range="endofrange", startref="ix_ch09-asciidoc2")))(((range="endofrange", startref="ix_ch09-asciidoc1")))

=== 貨幣ではないオルトチェーン

((("chains, alternative","noncurrency", id="ix_ch09-asciidoc5", range="startofrange")))((("non-currency alt chains", id="ix_ch09-asciidoc6", range="startofrange")))折るとチェーンは、ブロックチェーンのデザインパターンの代替の仕組みであり、それは一義的には貨幣として使われていない。多くは貨幣を含むが、その貨幣は他の何かを導入するためのトークンとして使われる。例えば、資源や、契約としてだ。その貨幣は、言い換えれば、プラットフォームの主要な点ではなく、2番目の機能である。  

==== Namecoin

namecoinはビットコインノードの最初のフォークだった。Namecoinは分散形のキーバリューストアであり、ブロックチェーンを使った輸送プラットフォームである。グローバルなドメイン名のレジストリーとなっており、インターネット上のドメイン・ネームレジストレーションシステムと似ている。ネームコインは、現在は、DNSの代替案として作成されており、ルートレベルのドメイン名は.bitとなっている。Namecoinは、ドメイン名の登録と、名前空間においてのキーバリューの組みの登録に使われている。Emailアドレスや、暗号キーや、SSL証明や、ファイルの署名、投票システム、株式の証明、そして他の数えきれない程のアプリケーションに使われる。 

NamecoinのシステムはNamecoinの通貨を含んでおり(NMC)、トランザクションフィーを登録と名前の移管のために使う。現在の価格では、その0.01NMCか凡そ1USセントを名前を登録するフィーのために使われる。Bitcoinと同じように、そのフィーはNamecoinのマイナーに獲得される。

Namecoinの基本的なパラメーターはビットコインと同一である。  

* Block生成時間: 10分
* 貨幣の総量: 2140年迄に 2100万NMC
* コンセンサスアルゴリズム: SHA256のProof of work
* 市場規模: 2014年中旬に1000万ドル

Namecoinの名前空間は制限されていない、そして誰でもどんな名前でもどんな方法でも登録できる。しかしながら、ブロックチェーンから読む時に、アプリケーションレベルのソフトウェアがどのように読みだすのか、そしてそこからどう進むのかを知っているために、特定の名前空間は合意された仕様を持っている。もし形式が間違っていれば、どのような特定の名前空間から読み出すために使おうとしているどのようなソフトウェアがエラーを吐き出すことになる。よく知られている名前空間は下記である。

* +d/+ は +.bit+ ドメインのための名前空間
+id/+ は個人のIDを保存するための名前空間。例えばemail addresや、PGPのキー等
+u/+ は追加で、より構造化された、IDを保存するための定義(Openspecに基づく)

((("blockchains","Namecoin")))NamecoinのクライアントはBitcoinのコアととても良く似ている。何故ならば同じソースコードから出来ているからだ。インストールの際に、クライアントはNamecoinのブロックチェーンをダウンロードし、クエリと、名前の登録が出来るようになる。3つの主要なコマンドがある。((("Namecoin","commands"))) 

+name_new+:: クエリーを送るか、名前の事前登録を行う。
+name_firstupdate+:: 名前を登録し、登録状態を公開する。
+name_update+:: 名前登録の詳細を変更し、リフレッシュする。

例えば、 +mastering-bitcoin.bit+のドメインを登録しようと思ったら、我々は下記のように +name_new+ のコマンドを使用する。

[source,bash]
----
$ namecoind name_new d/mastering-bitcoin
----
[source,json]
----
[
    "21cbab5b1241c6d1a6ad70a2416b3124eb883ac38e423e5ff591d1968eb6664a",
    "a05555e0fc56c023"
]
----

+name_new+ コマンドは、名前を登録し、その名前のハッシュと、ランダムなキーを結びつける。+name_new+の返り値となる2つのストリングは、ハッシュとランダムなキーである。（+a05555e0fc56c023+ は先行している例のコマンド）は公に名前を登録するために使われることが出来ます。一旦主張がNamecoinのブロックチェーン上に登録されると、それは+name_firstupdate+のコマンドによって、ランダムキーを供給されて公に登録されます。

----
$ namecoind name_firstupdate d/mastering-bitcoin a05555e0fc56c023 "{"map": {"www": {"ip":"1.2.3.4"}}}}"
b7a2e59c0a26e5e2664948946ebeca1260985c2f616ba579e6bc7f35ec234b01
----

この例は、+www.mastering-bitcoin.bit+ をIPアドレスの1.2.3.4にマッピングする。返り値となるハッシュはトランザクションIDであり、それはこの登録を追跡するために使われる事が出来る。そして、+name_list+のコマンドを走らせることで、どの名前が登録されているかを知ることが出来る。

----
$ namecoind name_list
----
====
[source,json]
----
[
    {
        "name" : "d/mastering-bitcoin",
        "value" : "{map: {www: {ip:1.2.3.4}}}}",
        "address" : "NCccBXrRUahAGrisBA1BLPWQfSrups8Geh",
        "expires_in" : 35929
    }
]
----
====

ネームコインの登録は、36,000ブロックごとに更新される必要がある。（およそ200日から250日）その+name_update+のコマンドは、何もフィーの必要がなく、それゆえにネームコインのドメインを新しくするのは無料である。第三者のプロバイダーが登録をコントロールし、自動的に更新することが出来る。そして、ウェブのインターフェースを通じて小さなフィーで更新できる。第三者のプロバイダーとともに、ネームコインのクライアントを走らせなくて済むようになる、しかし独立したネームコインによって提供される独立したコントロールをを失うこととなる 

==== Ethereum

((("contracts, in Ethereum"))) Ethereumは、ブロックチェーンの台帳上において、チューリング完全なコントラクトのプロセスと、それを実行するプラットフォームだ。ビットコインの複製ではなく、完全に独立した仕様と実装を持っている。Ethereumは、組み込みの通貨を持っており、それは_ether_と呼ばれている。_ether_は、コントラクトの実行のために必要なものだ。Ethereumのブロックチェーンの記録は、_contract_であり、それは低位の言語、バイトコードのようなチューリング完全なコードで書かれる。重要な事は、コントラクトはEthereumシステム上で動くプログラムであることだ。Ethereumのコントラクトは、データを保存することが出来、Etherの支払いを送ったり受け取る事、そして無限の長さのコンピュテーションを、分散形の自律的なソフトウェアのエージェントとして実行することが出来る(それ故にチューリング完全）

Ethereumはとても複雑な、他のオルトチェーン自身では実装できないようなシステムを実装することが出来る。例えば、Namecoinのような名前登録のスマートコントラクトは、下記のようにEthereumで書ける。 (より正確に言えば、Ethereumコードにコンパイルされる高位の言語で書ける。) (((range="endofrange", startref="ix_ch09-asciidoc6")))(((range="endofrange", startref="ix_ch09-asciidoc5")))

[source,python]
----
if !contract.storage[msg.data[0]]: # Is the key not yet taken? 
    # Then take it!
    contract.storage[msg.data[0]] = msg.data[1]
    return(1)
else:

    return(0) // Otherwise do nothing
----

=== 未来の通貨

次世代の暗号通貨は全般的に、将来のビットコインよりも見通しが明るくさえある。ビットコインは完全に新しい分散形の組織の形式を導入し、何百もの驚くべきイノベーションを生み出している。分散形の科学的なシステムから、金融、経済、嘉芸、中央バンキング、そしてコーポレート・ガバナンス迄だ。多くの人類の活動で、以前は中央集権的な組織や、機構が権威ある、もしくは信頼されている権利が必要とされてきたが、今や分散させることが出来る。ブロックチェーンとコンセンサスシステムの発明は、権力の集中や、腐敗や、規制による封じ込めが起きる機会を取り除き、組織と大きな規模のシステムの協調のコストを大きく削減することとなる。 