[preface]
== Hızlı Sözlük

Bu hızlı sözlük bitcoinle ilgili kullanılan bir çok terimi içermektedir. Bu terimler kitap boyunca kullanılmıştır, bir terimin anlamına bakmanız gerekirse diye bunu imleyin.

adres:
    Bir bitcoin adresi şunun gibi görünür: +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. "1" (sayı olan) ile başlayan harf ve numaraların dizgesinden oluşur. Aynı e-posta adresinizi verip başkalarından size e-posta göndermelerini istediğinizdeki gibi başkalarından sizin bitcoin adresinize bitcoin göndermelerini isteyebilirsiniz. ((("bitcoin address")))((("address", see="bitcoin address")))((("public key", see="bitcoin address")))

bip:
    Bitcoin Geliştirme Önerileri. Bitcoin topluluğu üyeleri bitcoini geliştirmek için bir dizi öneri sundu. Örneğin, BIP0021 bitcoin tek tip kaynak tanımlayıcı[uniform resource identifier(URI)] planını geliştirmek için sunulan bir öneridir.((("bip"))) 

bitcoin:
    Para birimi(madeni para), ağ ve yazılımın adı.((("bitcoin"))) 

blok:
    A grouping of transactions, marked with a timestamp, and a fingerprint of the previous block. The block header is hashed to produce a proof of work, thereby validating the transactions. Valid blocks are added to the main blockchain by network consensus.((("block")))

blok zinciri:
	A list of validated blocks, each linking to its predecessor all the way to the genesis block.((("blockchain")))
	
doğrulamalar:
	Once a transaction is included in a block, it has one confirmation. As soon as _another_ block is mined on the same blockchain, the transaction has two confirmations, and so on. Six or more confirmations is considered sufficient proof that a transaction cannot be reversed.((("confirmations")))

difficulty::
	A network-wide setting that controls how much computation is required to produce a proof of work.((("difficulty")))

zorluk hedefi:
 	A difficulty at which all the computation in the network will find blocks approximately every 10 minutes.((("target difficulty")))

zorluğun yeniden belirlenmesi:
	A network-wide recalculation of the difficulty that occurs once every 2,106 blocks and considers the hashing power of the previous 2,106 blocks.((("difficulty retargeting")))
	
ücretler:
	The sender of a transaction often includes a fee to the network for processing the requested transaction.  Most transactions require a minimum fee of 0.5 mBTC.((("fees")))

özet:
	A digital fingerprint of some binary input.((("hash")))

başlangıç bloğu:
	The first block in the blockchain, used to initialize the cryptocurrency.((("genesis block")))
	
madenci:
A network node that finds valid proof of work for new blocks, by repeated hashing.((("miner")))

ağ:
A peer-to-peer network that propagates transactions and blocks to every bitcoin node on the network.((("network")))
	
İş-Kanıtı::
	A piece of data that requires significant computation to find. In bitcoin, miners must find a numeric solution to the SHA256 algorithm that meets a network-wide target, the difficulty target. ((("proof-of-work")))

ödül::
An amount included in each new block as a reward by the network to the miner who found the Proof-Of-Work solution. It is currently 25BTC per block.((("reward")))

gizli anahtar (diğer bir deyişle özel anahtar)::
	The secret number that unlocks bitcoins sent to the corresponding address.  A secret key looks like +5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh+.((("secret key")))((("private key", see="secret key")))
	
işlem::
In simple terms, a transfer of bitcoins from one address to another. More precisely, a transaction is a signed data structure expressing a transfer of value. Transactions are transmitted over the bitcoin network, collected by miners, and included into blocks, made permanent on the blockchain.((("transaction")))

cüzdan:
Bitcoin adreslerinizi ve özel anahtarlarınızı saklayan yazılımdır. Bitcoin göndermek, almak ve saklamak için kullanılır. ((("wallet"))) 